// Auto-built from VOCAB_WORDS_RU_300_слов_синонимы.docx (task #51).
// Synonyms come verbatim from the source document; only timerSeconds is
// recomputed from difficulty per the spec (1→60, 2→40, 3→20).

export type PartOfSpeech = 'noun' | 'verb' | 'adjective';

export interface VocabWord {
  id: string;
  word: string;
  partOfSpeech: PartOfSpeech;
  synonyms: string[];
  timerSeconds: number;
  lang: 'ru';
  difficulty: 1 | 2 | 3;
}

export const VOCAB_WORDS_RU: VocabWord[] = [
  // СУЩЕСТВИТЕЛЬНЫЕ
  { id:'n001', word:'Радость', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['счастье', 'восторг', 'ликование', 'блаженство', 'эйфория', 'удовольствие', 'веселье', 'торжество'],
    timerSeconds:40 },
  { id:'n002', word:'Страх', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['ужас', 'тревога', 'паника', 'боязнь', 'испуг', 'опасение', 'робость', 'трепет'],
    timerSeconds:40 },
  { id:'n003', word:'Смелость', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['храбрость', 'отвага', 'мужество', 'бесстрашие', 'решимость', 'доблесть', 'дерзость', 'героизм'],
    timerSeconds:40 },
  { id:'n004', word:'Мудрость', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['разум', 'рассудительность', 'проницательность', 'дальновидность', 'зрелость', 'опытность', 'благоразумие', 'прозорливость'],
    timerSeconds:40 },
  { id:'n005', word:'Победа', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['триумф', 'успех', 'достижение', 'выигрыш', 'первенство', 'превосходство', 'торжество', 'завоевание'],
    timerSeconds:40 },
  { id:'n006', word:'Цель', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['задача', 'намерение', 'замысел', 'стремление', 'ориентир', 'план', 'миссия', 'назначение'],
    timerSeconds:40 },
  { id:'n007', word:'Идея', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['мысль', 'замысел', 'концепция', 'задумка', 'план', 'представление', 'гипотеза', 'соображение'],
    timerSeconds:40 },
  { id:'n008', word:'Мечта', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['желание', 'грёза', 'стремление', 'надежда', 'идеал', 'видение', 'замысел', 'фантазия'],
    timerSeconds:40 },
  { id:'n009', word:'Успех', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['достижение', 'удача', 'победа', 'результат', 'триумф', 'прорыв', 'свершение', 'признание'],
    timerSeconds:40 },
  { id:'n010', word:'Ошибка', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['промах', 'неточность', 'просчёт', 'оплошность', 'заблуждение', 'недочёт', 'погрешность', 'сбой'],
    timerSeconds:40 },
  { id:'n011', word:'Вопрос', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['запрос', 'проблема', 'тема', 'задача', 'дилемма', 'предмет', 'пункт', 'обращение'],
    timerSeconds:40 },
  { id:'n012', word:'Ответ', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['решение', 'разъяснение', 'пояснение', 'реакция', 'отклик', 'реплика', 'возражение', 'аргумент'],
    timerSeconds:40 },
  { id:'n013', word:'Разговор', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['беседа', 'диалог', 'общение', 'обсуждение', 'переговоры', 'разъяснение', 'дискуссия', 'полемика'],
    timerSeconds:40 },
  { id:'n014', word:'Речь', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['выступление', 'монолог', 'оратория', 'обращение', 'доклад', 'изложение', 'говорение', 'высказывание'],
    timerSeconds:40 },
  { id:'n015', word:'Голос', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['звучание', 'тон', 'тембр', 'интонация', 'зов', 'речь', 'произношение', 'звук'],
    timerSeconds:40 },
  { id:'n016', word:'Слово', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['лексема', 'выражение', 'термин', 'название', 'речение', 'фраза', 'обозначение', 'понятие'],
    timerSeconds:40 },
  { id:'n017', word:'Текст', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['материал', 'изложение', 'сочинение', 'рукопись', 'статья', 'контент', 'письмо', 'формулировка'],
    timerSeconds:40 },
  { id:'n018', word:'История', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['рассказ', 'повесть', 'сюжет', 'случай', 'событие', 'хроника', 'биография', 'предание'],
    timerSeconds:40 },
  { id:'n019', word:'Внимание', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['сосредоточенность', 'концентрация', 'интерес', 'наблюдательность', 'чуткость', 'забота', 'участие', 'бдительность'],
    timerSeconds:40 },
  { id:'n020', word:'Память', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['воспоминание', 'запоминание', 'ретроспекция', 'помнящность', 'сохранение', 'припоминание', 'опыт', 'след'],
    timerSeconds:40 },
  { id:'n021', word:'Время', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['период', 'срок', 'момент', 'эпоха', 'промежуток', 'пора', 'длительность', 'отрезок'],
    timerSeconds:40 },
  { id:'n022', word:'Скорость', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['быстрота', 'темп', 'проворность', 'стремительность', 'ускорение', 'оперативность', 'резвость', 'динамика'],
    timerSeconds:40 },
  { id:'n023', word:'Сила', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['мощь', 'энергия', 'крепость', 'могущество', 'влияние', 'напор', 'стойкость', 'потенциал'],
    timerSeconds:40 },
  { id:'n024', word:'Слабость', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['бессилие', 'уязвимость', 'хрупкость', 'немощь', 'уступчивость', 'изъян', 'недостаток', 'беспомощность'],
    timerSeconds:40 },
  { id:'n025', word:'Красота', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['прелесть', 'очарование', 'изящество', 'великолепие', 'гармония', 'грация', 'привлекательность', 'совершенство'],
    timerSeconds:40 },
  { id:'n026', word:'Правда', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['истина', 'действительность', 'реальность', 'подлинность', 'честность', 'искренность', 'факт', 'достоверность'],
    timerSeconds:40 },
  { id:'n027', word:'Ложь', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['обман', 'неправда', 'вымысел', 'фальшь', 'клевета', 'дезинформация', 'искажение', 'мистификация'],
    timerSeconds:40 },
  { id:'n028', word:'Доверие', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['вера', 'уверенность', 'надежность', 'расположение', 'кредит', 'убеждённость', 'признание', 'безопасность'],
    timerSeconds:40 },
  { id:'n029', word:'Опыт', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['практика', 'навык', 'знание', 'стаж', 'умение', 'мастерство', 'компетенция', 'подготовка'],
    timerSeconds:40 },
  { id:'n030', word:'Навык', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['умение', 'мастерство', 'способность', 'компетенция', 'приём', 'практика', 'искусность', 'квалификация'],
    timerSeconds:40 },
  { id:'n031', word:'Знание', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['понимание', 'сведение', 'осведомлённость', 'эрудиция', 'информация', 'компетенция', 'грамотность', 'познание'],
    timerSeconds:40 },
  { id:'n032', word:'Мысль', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['идея', 'соображение', 'размышление', 'суждение', 'помысел', 'представление', 'догадка', 'вывод'],
    timerSeconds:40 },
  { id:'n033', word:'Аргумент', partOfSpeech:'noun', difficulty:1, lang:'ru',
    synonyms:['довод', 'обоснование', 'доказательство', 'мотив', 'причина', 'основание', 'подтверждение', 'резон'],
    timerSeconds:40 },
  { id:'n034', word:'Пример', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['образец', 'модель', 'случай', 'иллюстрация', 'эталон', 'прецедент', 'демонстрация', 'вариант'],
    timerSeconds:30 },
  { id:'n035', word:'Причина', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['основание', 'мотив', 'повод', 'источник', 'фактор', 'предпосылка', 'обстоятельство', 'корень'],
    timerSeconds:30 },
  { id:'n036', word:'Результат', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['итог', 'вывод', 'последствие', 'эффект', 'плод', 'достижение', 'исход', 'продукт'],
    timerSeconds:30 },
  { id:'n037', word:'План', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['стратегия', 'замысел', 'проект', 'схема', 'программа', 'намерение', 'расписание', 'концепция'],
    timerSeconds:30 },
  { id:'n038', word:'Стратегия', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['план', 'тактика', 'курс', 'подход', 'метод', 'система', 'замысел', 'линия'],
    timerSeconds:30 },
  { id:'n039', word:'Решение', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['выбор', 'ответ', 'постановление', 'выход', 'вердикт', 'заключение', 'развязка', 'метод'],
    timerSeconds:30 },
  { id:'n040', word:'Проблема', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['трудность', 'сложность', 'задача', 'вопрос', 'препятствие', 'загвоздка', 'конфликт', 'дилемма'],
    timerSeconds:30 },
  { id:'n041', word:'Возможность', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['шанс', 'перспектива', 'вероятность', 'потенциал', 'вариант', 'способ', 'ресурс', 'условие'],
    timerSeconds:30 },
  { id:'n042', word:'Препятствие', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['барьер', 'помеха', 'преграда', 'трудность', 'заслон', 'ограничение', 'проблема', 'противодействие'],
    timerSeconds:30 },
  { id:'n043', word:'Поддержка', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['помощь', 'содействие', 'опора', 'защита', 'одобрение', 'участие', 'покровительство', 'подкрепление'],
    timerSeconds:30 },
  { id:'n044', word:'Критика', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['замечание', 'оценка', 'разбор', 'анализ', 'порицание', 'обсуждение', 'рецензия', 'осуждение'],
    timerSeconds:30 },
  { id:'n045', word:'Похвала', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['одобрение', 'комплимент', 'признание', 'восхищение', 'ласка', 'хвала', 'поощрение', 'восторг'],
    timerSeconds:30 },
  { id:'n046', word:'Уверенность', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['убеждённость', 'решимость', 'самообладание', 'спокойствие', 'надежность', 'твёрдость', 'убеждение', 'смелость'],
    timerSeconds:30 },
  { id:'n047', word:'Сомнение', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['неуверенность', 'колебание', 'подозрение', 'недоверие', 'скепсис', 'опасение', 'нерешительность', 'неясность'],
    timerSeconds:30 },
  { id:'n048', word:'Энергия', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['сила', 'бодрость', 'активность', 'мощь', 'заряд', 'ресурс', 'тонус', 'напор'],
    timerSeconds:30 },
  { id:'n049', word:'Настроение', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['состояние', 'самочувствие', 'расположение', 'дух', 'эмоция', 'тон', 'атмосфера', 'настрой'],
    timerSeconds:30 },
  { id:'n050', word:'Характер', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['нрав', 'темперамент', 'особенность', 'натура', 'склад', 'индивидуальность', 'личность', 'свойство'],
    timerSeconds:30 },
  { id:'n051', word:'Личность', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['индивидуальность', 'персона', 'человек', 'субъект', 'характер', 'натура', 'фигура', 'самость'],
    timerSeconds:30 },
  { id:'n052', word:'Команда', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['коллектив', 'группа', 'отряд', 'состав', 'экипаж', 'сообщество', 'союз', 'бригада'],
    timerSeconds:30 },
  { id:'n053', word:'Лидер', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['руководитель', 'вождь', 'глава', 'наставник', 'ведущий', 'командир', 'организатор', 'предводитель'],
    timerSeconds:30 },
  { id:'n054', word:'Ученик', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['студент', 'обучающийся', 'подопечный', 'слушатель', 'последователь', 'новичок', 'воспитанник', 'курсант'],
    timerSeconds:30 },
  { id:'n055', word:'Учитель', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['педагог', 'наставник', 'преподаватель', 'ментор', 'инструктор', 'тренер', 'воспитатель', 'лектор'],
    timerSeconds:30 },
  { id:'n056', word:'Сцена', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['площадка', 'помост', 'арена', 'эстрада', 'подмостки', 'пространство', 'платформа', 'место'],
    timerSeconds:30 },
  { id:'n057', word:'Публика', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['аудитория', 'зрители', 'слушатели', 'толпа', 'общество', 'зал', 'собрание', 'публикум'],
    timerSeconds:30 },
  { id:'n058', word:'Выступление', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['доклад', 'речь', 'презентация', 'номер', 'обращение', 'монолог', 'показ', 'представление'],
    timerSeconds:30 },
  { id:'n059', word:'Тренировка', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['занятие', 'практика', 'упражнение', 'репетиция', 'подготовка', 'разминка', 'отработка', 'тренинг'],
    timerSeconds:30 },
  { id:'n060', word:'Игра', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['развлечение', 'соревнование', 'матч', 'забава', 'партия', 'квест', 'испытание', 'затея'],
    timerSeconds:30 },
  { id:'n061', word:'Уровень', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['ступень', 'этап', 'ранг', 'стадия', 'порог', 'пласт', 'категория', 'фаза'],
    timerSeconds:30 },
  { id:'n062', word:'Задание', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['упражнение', 'задача', 'поручение', 'миссия', 'испытание', 'работа', 'пункт', 'тест'],
    timerSeconds:30 },
  { id:'n063', word:'Правило', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['норма', 'закон', 'принцип', 'условие', 'требование', 'порядок', 'регламент', 'установка'],
    timerSeconds:30 },
  { id:'n064', word:'Свобода', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['независимость', 'воля', 'самостоятельность', 'простор', 'раскрепощение', 'автономия', 'вольность', 'освобождение'],
    timerSeconds:30 },
  { id:'n065', word:'Ответственность', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['обязанность', 'долг', 'обязательство', 'серьёзность', 'подотчётность', 'надёжность', 'поручительство', 'вина'],
    timerSeconds:30 },
  { id:'n066', word:'Дисциплина', partOfSpeech:'noun', difficulty:2, lang:'ru',
    synonyms:['порядок', 'организованность', 'собранность', 'режим', 'самоконтроль', 'строгость', 'система', 'подчинение'],
    timerSeconds:30 },
  { id:'n067', word:'Концентрация', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['сосредоточение', 'внимание', 'собранность', 'фокус', 'напряжение', 'погружение', 'сгущение', 'скопление'],
    timerSeconds:20 },
  { id:'n068', word:'Мотивация', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['стимул', 'побуждение', 'интерес', 'желание', 'драйв', 'намерение', 'воодушевление', 'импульс'],
    timerSeconds:20 },
  { id:'n069', word:'Прогресс', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['развитие', 'рост', 'улучшение', 'движение', 'продвижение', 'успех', 'эволюция', 'сдвиг'],
    timerSeconds:20 },
  { id:'n070', word:'Развитие', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['рост', 'совершенствование', 'прогресс', 'эволюция', 'формирование', 'расширение', 'становление', 'улучшение'],
    timerSeconds:20 },
  { id:'n071', word:'Творчество', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['созидание', 'креативность', 'искусство', 'изобретательность', 'самовыражение', 'фантазия', 'новаторство', 'творение'],
    timerSeconds:20 },
  { id:'n072', word:'Воображение', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['фантазия', 'представление', 'выдумка', 'образность', 'мечтательность', 'видение', 'изобретательность', 'мысленный образ'],
    timerSeconds:20 },
  { id:'n073', word:'Фокус', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['внимание', 'центр', 'сосредоточение', 'прицел', 'направление', 'концентрация', 'точка', 'акцент'],
    timerSeconds:20 },
  { id:'n074', word:'Интерес', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['любопытство', 'увлечение', 'внимание', 'симпатия', 'заинтересованность', 'тяга', 'склонность', 'польза'],
    timerSeconds:20 },
  { id:'n075', word:'Любопытство', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['интерес', 'пытливость', 'любознательность', 'вопросительность', 'жажда знания', 'исследовательность', 'заинтересованность', 'внимание'],
    timerSeconds:20 },
  { id:'n076', word:'Терпение', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['выдержка', 'стойкость', 'самообладание', 'спокойствие', 'усидчивость', 'сдержанность', 'настойчивость', 'смирение'],
    timerSeconds:20 },
  { id:'n077', word:'Настойчивость', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['упорство', 'упорность', 'целеустремлённость', 'решимость', 'постоянство', 'неотступность', 'терпение', 'твёрдость'],
    timerSeconds:20 },
  { id:'n078', word:'Вдохновение', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['воодушевление', 'подъём', 'озарение', 'порыв', 'энтузиазм', 'стимул', 'импульс', 'крылья'],
    timerSeconds:20 },
  { id:'n079', word:'Темп', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['скорость', 'ритм', 'быстрота', 'пульс', 'ход', 'динамика', 'размеренность', 'интенсивность'],
    timerSeconds:20 },
  { id:'n080', word:'Ритм', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['темп', 'пульс', 'размер', 'такт', 'цикличность', 'периодичность', 'движение', 'чередование'],
    timerSeconds:20 },
  { id:'n081', word:'Пауза', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['перерыв', 'остановка', 'промежуток', 'задержка', 'молчание', 'антракт', 'передышка', 'интервал'],
    timerSeconds:20 },
  { id:'n082', word:'Интонация', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['тон', 'мелодика', 'звучание', 'окраска', 'выразительность', 'акцент', 'настрой', 'модуляция'],
    timerSeconds:20 },
  { id:'n083', word:'Произношение', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['артикуляция', 'дикция', 'звучание', 'выговаривание', 'акцент', 'фонетика', 'речь', 'озвучивание'],
    timerSeconds:20 },
  { id:'n084', word:'Дикция', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['произношение', 'артикуляция', 'чёткость', 'выговор', 'звучание', 'речь', 'ясность', 'фонетика'],
    timerSeconds:20 },
  { id:'n085', word:'Тавтология', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['повтор', 'дублирование', 'избыточность', 'однообразие', 'повторяемость', 'плеоназм', 'монотонность', 'зацикливание'],
    timerSeconds:20 },
  { id:'n086', word:'Синоним', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['аналог', 'замена', 'эквивалент', 'вариант', 'соответствие', 'подобие', 'сходство', 'лексический дублёр'],
    timerSeconds:20 },
  { id:'n087', word:'Богатство', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['изобилие', 'достаток', 'роскошь', 'обилие', 'состояние', 'полнота', 'щедрость', 'разнообразие'],
    timerSeconds:20 },
  { id:'n088', word:'Разнообразие', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['многообразие', 'вариативность', 'пестрота', 'богатство', 'различие', 'неоднородность', 'обилие', 'широта'],
    timerSeconds:20 },
  { id:'n089', word:'Ясность', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['понятность', 'чёткость', 'прозрачность', 'очевидность', 'определённость', 'доходчивость', 'внятность', 'ясновидность'],
    timerSeconds:20 },
  { id:'n090', word:'Точность', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['аккуратность', 'верность', 'чёткость', 'меткость', 'достоверность', 'безошибочность', 'определённость', 'правильность'],
    timerSeconds:20 },
  { id:'n091', word:'Грамотность', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['образованность', 'правильность', 'компетентность', 'знание', 'культура', 'осведомлённость', 'эрудиция', 'подготовленность'],
    timerSeconds:20 },
  { id:'n092', word:'Культура', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['цивилизованность', 'воспитанность', 'образованность', 'традиция', 'наследие', 'искусство', 'утончённость', 'развитость'],
    timerSeconds:20 },
  { id:'n093', word:'Уважение', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['почтение', 'признание', 'почтительность', 'уважительность', 'пиетет', 'внимание', 'почёт', 'тактичность'],
    timerSeconds:20 },
  { id:'n094', word:'Честность', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['правдивость', 'искренность', 'порядочность', 'прямота', 'добросовестность', 'открытость', 'неподкупность', 'чистота'],
    timerSeconds:20 },
  { id:'n095', word:'Искренность', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['открытость', 'честность', 'сердечность', 'прямота', 'неподдельность', 'естественность', 'душевность', 'правдивость'],
    timerSeconds:20 },
  { id:'n096', word:'Обаяние', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['очарование', 'притягательность', 'харизма', 'прелесть', 'симпатичность', 'магнетизм', 'шарм', 'обаятельность'],
    timerSeconds:20 },
  { id:'n097', word:'Харизма', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['обаяние', 'притягательность', 'магнетизм', 'влияние', 'авторитет', 'сила личности', 'очарование', 'лидерство'],
    timerSeconds:20 },
  { id:'n098', word:'Влияние', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['воздействие', 'эффект', 'власть', 'авторитет', 'давление', 'роль', 'значение', 'сила'],
    timerSeconds:20 },
  { id:'n099', word:'Признание', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['одобрение', 'уважение', 'известность', 'похвала', 'слава', 'подтверждение', 'принятие', 'авторитет'],
    timerSeconds:20 },
  { id:'n100', word:'Слава', partOfSpeech:'noun', difficulty:3, lang:'ru',
    synonyms:['известность', 'популярность', 'почёт', 'репутация', 'признание', 'знаменитость', 'триумф', 'величие'],
    timerSeconds:20 },
  // ГЛАГОЛЫ
  { id:'v001', word:'Говорить', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['произносить', 'высказывать', 'излагать', 'рассказывать', 'повествовать', 'объяснять', 'сообщать', 'вещать'],
    timerSeconds:40 },
  { id:'v002', word:'Думать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['размышлять', 'рассуждать', 'обдумывать', 'анализировать', 'соображать', 'полагать', 'разбирать', 'созерцать'],
    timerSeconds:40 },
  { id:'v003', word:'Побеждать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['выигрывать', 'одолеть', 'превосходить', 'торжествовать', 'доминировать', 'завоёвывать', 'опережать', 'обгонять'],
    timerSeconds:40 },
  { id:'v004', word:'Создавать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['творить', 'строить', 'формировать', 'конструировать', 'изобретать', 'производить', 'основывать', 'генерировать'],
    timerSeconds:40 },
  { id:'v005', word:'Вдохновлять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['мотивировать', 'воодушевлять', 'окрылять', 'побуждать', 'стимулировать', 'зажигать', 'поощрять', 'пробуждать'],
    timerSeconds:40 },
  { id:'v006', word:'Слушать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['внимать', 'заслушивать', 'выслушивать', 'прислушиваться', 'слышать', 'улавливать', 'перенимать', 'воспринимать'],
    timerSeconds:40 },
  { id:'v007', word:'Понимать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['осознавать', 'постигать', 'уяснять', 'разбирать', 'схватывать', 'вникать', 'усваивать', 'разуметь'],
    timerSeconds:40 },
  { id:'v008', word:'Учиться', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['обучаться', 'осваивать', 'изучать', 'постигать', 'тренироваться', 'практиковаться', 'заниматься', 'усваивать'],
    timerSeconds:40 },
  { id:'v009', word:'Объяснять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['разъяснять', 'толковать', 'пояснять', 'растолковывать', 'комментировать', 'интерпретировать', 'излагать', 'раскрывать'],
    timerSeconds:40 },
  { id:'v010', word:'Доказывать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['обосновывать', 'подтверждать', 'аргументировать', 'демонстрировать', 'устанавливать', 'удостоверять', 'показывать', 'свидетельствовать'],
    timerSeconds:40 },
  { id:'v011', word:'Спрашивать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['интересоваться', 'осведомляться', 'выяснять', 'расспрашивать', 'запрашивать', 'допытываться', 'узнавать', 'вопрошать'],
    timerSeconds:40 },
  { id:'v012', word:'Отвечать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['реагировать', 'откликаться', 'разъяснять', 'пояснять', 'сообщать', 'возражать', 'комментировать', 'реплицировать'],
    timerSeconds:40 },
  { id:'v013', word:'Читать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['прочитывать', 'изучать', 'просматривать', 'декламировать', 'озвучивать', 'разбирать', 'перечитывать', 'произносить'],
    timerSeconds:40 },
  { id:'v014', word:'Писать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['записывать', 'сочинять', 'формулировать', 'излагать', 'черчить', 'фиксировать', 'создавать', 'набирать'],
    timerSeconds:40 },
  { id:'v015', word:'Играть', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['соревноваться', 'развлекаться', 'исполнять', 'разыгрывать', 'участвовать', 'действовать', 'выступать', 'забавляться'],
    timerSeconds:40 },
  { id:'v016', word:'Тренироваться', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['заниматься', 'упражняться', 'практиковаться', 'готовиться', 'отрабатывать', 'разминаться', 'совершенствоваться', 'репетировать'],
    timerSeconds:40 },
  { id:'v017', word:'Развиваться', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['расти', 'совершенствоваться', 'прогрессировать', 'эволюционировать', 'улучшаться', 'формироваться', 'расширяться', 'становиться'],
    timerSeconds:40 },
  { id:'v018', word:'Улучшать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['совершенствовать', 'исправлять', 'усиливать', 'повышать', 'модернизировать', 'обогащать', 'развивать', 'доводить'],
    timerSeconds:40 },
  { id:'v019', word:'Повторять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['дублировать', 'воспроизводить', 'пересказывать', 'твердить', 'копировать', 'репетировать', 'возобновлять', 'перечислять'],
    timerSeconds:40 },
  { id:'v020', word:'Запоминать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['запечатлевать', 'заучивать', 'фиксировать', 'усваивать', 'сохранять', 'записывать', 'помнить', 'зазубривать'],
    timerSeconds:40 },
  { id:'v021', word:'Ошибаться', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['заблуждаться', 'промахиваться', 'просчитываться', 'спотыкаться', 'путаться', 'сбиваться', 'оступаться', 'неточничать'],
    timerSeconds:40 },
  { id:'v022', word:'Исправлять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['корректировать', 'чинить', 'улучшать', 'править', 'выправлять', 'устранять', 'редактировать', 'налаживать'],
    timerSeconds:40 },
  { id:'v023', word:'Выбирать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['отбирать', 'подбирать', 'предпочитать', 'решать', 'назначать', 'выделять', 'сортировать', 'избирать'],
    timerSeconds:40 },
  { id:'v024', word:'Начинать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['стартовать', 'приступать', 'запускать', 'открывать', 'затевать', 'заводить', 'инициировать', 'вводить'],
    timerSeconds:40 },
  { id:'v025', word:'Завершать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['заканчивать', 'оканчивать', 'завершать', 'финализировать', 'закрывать', 'прекращать', 'сворачивать', 'доводить'],
    timerSeconds:40 },
  { id:'v026', word:'Ускорять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['торопить', 'разгонять', 'ускорять', 'подгонять', 'форсировать', 'активизировать', 'стимулировать', 'приближать'],
    timerSeconds:40 },
  { id:'v027', word:'Замедлять', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['тормозить', 'сдерживать', 'медлить', 'задерживать', 'ослаблять', 'притормаживать', 'растягивать', 'замораживать'],
    timerSeconds:40 },
  { id:'v028', word:'Останавливать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['прекращать', 'останавливать', 'тормозить', 'прерывать', 'задерживать', 'блокировать', 'замораживать', 'сдерживать'],
    timerSeconds:40 },
  { id:'v029', word:'Продолжать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['возобновлять', 'длить', 'поддерживать', 'вести', 'развивать', 'тянуть', 'сохранять', 'пролонгировать'],
    timerSeconds:40 },
  { id:'v030', word:'Убеждать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['уговаривать', 'доказывать', 'склонять', 'заверять', 'внушать', 'аргументировать', 'уверять', 'переубеждать'],
    timerSeconds:40 },
  { id:'v031', word:'Спорить', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['дискутировать', 'возражать', 'полемизировать', 'препираться', 'доказывать', 'оспаривать', 'дебатировать', 'состязаться'],
    timerSeconds:40 },
  { id:'v032', word:'Докладывать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['сообщать', 'излагать', 'отчитываться', 'информировать', 'объявлять', 'рапортовать', 'рассказывать', 'доносить'],
    timerSeconds:40 },
  { id:'v033', word:'Презентовать', partOfSpeech:'verb', difficulty:1, lang:'ru',
    synonyms:['представлять', 'показывать', 'демонстрировать', 'излагать', 'выводить', 'объявлять', 'предъявлять', 'подавать'],
    timerSeconds:40 },
  { id:'v034', word:'Выступать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['говорить', 'докладывать', 'представлять', 'исполнять', 'обращаться', 'появляться', 'участвовать', 'декламировать'],
    timerSeconds:30 },
  { id:'v035', word:'Рассуждать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['размышлять', 'думать', 'анализировать', 'обсуждать', 'судить', 'соображать', 'разбирать', 'умозаключать'],
    timerSeconds:30 },
  { id:'v036', word:'Анализировать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['разбирать', 'исследовать', 'изучать', 'оценивать', 'рассматривать', 'сравнивать', 'проверять', 'осмысливать'],
    timerSeconds:30 },
  { id:'v037', word:'Сравнивать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['сопоставлять', 'соотносить', 'противопоставлять', 'сверять', 'анализировать', 'приравнивать', 'оценивать', 'сравнять'],
    timerSeconds:30 },
  { id:'v038', word:'Оценивать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['судить', 'измерять', 'анализировать', 'рассматривать', 'прикидывать', 'определять', 'расценивать', 'экспертировать'],
    timerSeconds:30 },
  { id:'v039', word:'Хвалить', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['одобрять', 'восхвалять', 'превозносить', 'поощрять', 'комплиментировать', 'славить', 'поддерживать', 'благодарить'],
    timerSeconds:30 },
  { id:'v040', word:'Критиковать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['осуждать', 'разбирать', 'порицать', 'оценивать', 'ругать', 'обсуждать', 'замечать', 'оспаривать'],
    timerSeconds:30 },
  { id:'v041', word:'Молчать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['умолкать', 'безмолвствовать', 'притихать', 'таиться', 'замыкаться', 'не говорить', 'затихать', 'сдерживаться'],
    timerSeconds:30 },
  { id:'v042', word:'Кричать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['орать', 'вопить', 'выкрикивать', 'звать', 'реветь', 'горланить', 'возглашать', 'скандировать'],
    timerSeconds:30 },
  { id:'v043', word:'Шептать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['нашёптывать', 'бормотать', 'говорить тихо', 'прошептывать', 'лепетать', 'шушукаться', 'шептаться', 'проговаривать'],
    timerSeconds:30 },
  { id:'v044', word:'Дышать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['вдыхать', 'выдыхать', 'дышаться', 'пыхтеть', 'сопеть', 'переводить дыхание', 'вентиллировать', 'дышать ровно'],
    timerSeconds:30 },
  { id:'v045', word:'Улыбаться', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['усмехаться', 'сиять', 'скалиться', 'радоваться', 'улыбнуться', 'светиться', 'ухмыляться', 'расцветать'],
    timerSeconds:30 },
  { id:'v046', word:'Смеяться', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['хохотать', 'улыбаться', 'заливаться', 'смеяться громко', 'потешаться', 'хихикать', 'гоготать', 'веселиться'],
    timerSeconds:30 },
  { id:'v047', word:'Бояться', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['страшиться', 'опасаться', 'тревожиться', 'пугаться', 'дрожать', 'робеть', 'паниковать', 'ужасаться'],
    timerSeconds:30 },
  { id:'v048', word:'Радоваться', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['ликовать', 'веселиться', 'торжествовать', 'наслаждаться', 'счастливиться', 'восторгаться', 'сиять', 'упиваться'],
    timerSeconds:30 },
  { id:'v049', word:'Стараться', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['пытаться', 'усердствовать', 'добиваться', 'стремиться', 'напрягаться', 'усиливаться', 'трудиться', 'успевать'],
    timerSeconds:30 },
  { id:'v050', word:'Достигать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['добиваться', 'получать', 'завоёвывать', 'добывать', 'осуществлять', 'доходить', 'приобретать', 'выполнять'],
    timerSeconds:30 },
  { id:'v051', word:'Планировать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['намечать', 'проектировать', 'предусматривать', 'рассчитывать', 'задумывать', 'организовывать', 'программировать', 'расписывать'],
    timerSeconds:30 },
  { id:'v052', word:'Организовывать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['устраивать', 'налаживать', 'координировать', 'создавать', 'собирать', 'упорядочивать', 'проводить', 'готовить'],
    timerSeconds:30 },
  { id:'v053', word:'Управлять', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['руководить', 'командовать', 'контролировать', 'вести', 'направлять', 'администрировать', 'регулировать', 'возглавлять'],
    timerSeconds:30 },
  { id:'v054', word:'Помогать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['содействовать', 'поддерживать', 'ассистировать', 'выручать', 'способствовать', 'облегчать', 'подсоблять', 'пособлять'],
    timerSeconds:30 },
  { id:'v055', word:'Мешать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['препятствовать', 'тормозить', 'затруднять', 'срывать', 'задерживать', 'блокировать', 'вредить', 'путать'],
    timerSeconds:30 },
  { id:'v056', word:'Вести', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['направлять', 'руководить', 'сопровождать', 'проводить', 'тащить', 'возглавлять', 'управлять', 'двигать'],
    timerSeconds:30 },
  { id:'v057', word:'Следовать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['идти', 'придерживаться', 'подчиняться', 'соблюдать', 'двигаться', 'поступать', 'направляться', 'следить'],
    timerSeconds:30 },
  { id:'v058', word:'Менять', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['изменять', 'заменять', 'перестраивать', 'обновлять', 'преобразовывать', 'варьировать', 'переключать', 'модифицировать'],
    timerSeconds:30 },
  { id:'v059', word:'Сохранять', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['беречь', 'удерживать', 'запоминать', 'оставлять', 'фиксировать', 'поддерживать', 'консервировать', 'хранить'],
    timerSeconds:30 },
  { id:'v060', word:'Терять', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['утрачивать', 'лишаться', 'ронять', 'проигрывать', 'упускать', 'забывать', 'расходовать', 'потерять'],
    timerSeconds:30 },
  { id:'v061', word:'Находить', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['обнаруживать', 'отыскивать', 'выявлять', 'разыскивать', 'добывать', 'получать', 'встречать', 'выискивать'],
    timerSeconds:30 },
  { id:'v062', word:'Искать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['разыскивать', 'выискивать', 'подбирать', 'исследовать', 'обнаруживать', 'спрашивать', 'искать ответ', 'отыскивать'],
    timerSeconds:30 },
  { id:'v063', word:'Строить', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['создавать', 'возводить', 'сооружать', 'конструировать', 'формировать', 'проектировать', 'налаживать', 'выстраивать'],
    timerSeconds:30 },
  { id:'v064', word:'Разрушать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['ломать', 'разбирать', 'уничтожать', 'крушить', 'сносить', 'подрывать', 'портить', 'расшатывать'],
    timerSeconds:30 },
  { id:'v065', word:'Открывать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['раскрывать', 'обнаруживать', 'начинать', 'отпирать', 'выявлять', 'открывать доступ', 'обнажать', 'запускать'],
    timerSeconds:30 },
  { id:'v066', word:'Закрывать', partOfSpeech:'verb', difficulty:2, lang:'ru',
    synonyms:['запирать', 'завершать', 'прикрывать', 'скрывать', 'перекрывать', 'оканчивать', 'замыкать', 'сворачивать'],
    timerSeconds:30 },
  { id:'v067', word:'Показывать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['демонстрировать', 'предъявлять', 'отображать', 'изображать', 'указывать', 'показываться', 'выявлять', 'раскрывать'],
    timerSeconds:20 },
  { id:'v068', word:'Скрывать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['прятать', 'утаивать', 'маскировать', 'засекречивать', 'покрывать', 'замалчивать', 'притворять', 'утапливать'],
    timerSeconds:20 },
  { id:'v069', word:'Зажигать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['воспламенять', 'включать', 'разжигать', 'освещать', 'воодушевлять', 'разогревать', 'запаливать', 'зажечь'],
    timerSeconds:20 },
  { id:'v070', word:'Гасить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['тушить', 'выключать', 'подавлять', 'успокаивать', 'приглушать', 'ослаблять', 'заглушать', 'ликвидировать'],
    timerSeconds:20 },
  { id:'v071', word:'Поднимать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['возвышать', 'приподнимать', 'увеличивать', 'подбирать', 'вздымать', 'развивать', 'улучшать', 'подносить'],
    timerSeconds:20 },
  { id:'v072', word:'Опускать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['снижать', 'ронять', 'спускать', 'уменьшать', 'опускаться', 'ослаблять', 'погружать', 'понижать'],
    timerSeconds:20 },
  { id:'v073', word:'Включать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['запускать', 'активировать', 'присоединять', 'добавлять', 'вводить', 'подключать', 'зажигать', 'заводить'],
    timerSeconds:20 },
  { id:'v074', word:'Выключать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['отключать', 'гасить', 'останавливать', 'деактивировать', 'обесточивать', 'прекращать', 'отсоединять', 'заглушать'],
    timerSeconds:20 },
  { id:'v075', word:'Запускать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['начинать', 'включать', 'инициировать', 'стартовать', 'активировать', 'пускать', 'открывать', 'заводить'],
    timerSeconds:20 },
  { id:'v076', word:'Обновлять', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['освежать', 'модернизировать', 'переписывать', 'улучшать', 'актуализировать', 'менять', 'заменять', 'перезагружать'],
    timerSeconds:20 },
  { id:'v077', word:'Проверять', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['контролировать', 'испытывать', 'тестировать', 'сверять', 'осматривать', 'оценивать', 'ревизовать', 'уточнять'],
    timerSeconds:20 },
  { id:'v078', word:'Считать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['подсчитывать', 'вычислять', 'рассчитывать', 'перечислять', 'полагать', 'думать', 'нумеровать', 'оценивать'],
    timerSeconds:20 },
  { id:'v079', word:'Зарабатывать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['получать', 'добывать', 'выручать', 'заслуживать', 'приобретать', 'накоплять', 'извлекать', 'наживать'],
    timerSeconds:20 },
  { id:'v080', word:'Тратить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['расходовать', 'транжирить', 'использовать', 'платить', 'издерживать', 'пускать', 'растрачивать', 'употреблять'],
    timerSeconds:20 },
  { id:'v081', word:'Покупать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['приобретать', 'закупать', 'брать', 'выкупать', 'заказывать', 'добывать', 'обзаводиться', 'оплачивать'],
    timerSeconds:20 },
  { id:'v082', word:'Продавать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['реализовывать', 'сбывать', 'торговать', 'отпускать', 'предлагать', 'распродавать', 'поставлять', 'обменивать'],
    timerSeconds:20 },
  { id:'v083', word:'Дарить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['преподносить', 'вручать', 'передавать', 'жаловать', 'презентовать', 'отдавать', 'одаривать', 'приносить'],
    timerSeconds:20 },
  { id:'v084', word:'Получать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['принимать', 'добывать', 'приобретать', 'зарабатывать', 'извлекать', 'обретать', 'получаться', 'выручать'],
    timerSeconds:20 },
  { id:'v085', word:'Любить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['обожать', 'ценить', 'нравиться', 'уважать', 'почитать', 'увлекаться', 'симпатизировать', 'дорожить'],
    timerSeconds:20 },
  { id:'v086', word:'Ненавидеть', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['презирать', 'не терпеть', 'отвращаться', 'враждовать', 'испытывать ненависть', 'гнушаться', 'злиться', 'недолюбливать'],
    timerSeconds:20 },
  { id:'v087', word:'Верить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['доверять', 'полагаться', 'считать', 'надеяться', 'убеждаться', 'принимать', 'исповедовать', 'вверяться'],
    timerSeconds:20 },
  { id:'v088', word:'Сомневаться', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['колебаться', 'не верить', 'подозревать', 'скептически относиться', 'опасаться', 'сомневаться в', 'нерешаться', 'раздумывать'],
    timerSeconds:20 },
  { id:'v089', word:'Рисковать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['осмеливаться', 'дерзать', 'ставить на кон', 'подвергаться', 'играть с огнём', 'решаться', 'пробовать', 'рисковать собой'],
    timerSeconds:20 },
  { id:'v090', word:'Пробовать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['пытаться', 'испытывать', 'тестировать', 'дегустировать', 'примерять', 'предпринимать', 'экспериментировать', 'начинать'],
    timerSeconds:20 },
  { id:'v091', word:'Мечтать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['грезить', 'желать', 'фантазировать', 'стремиться', 'воображать', 'надеяться', 'задумываться', 'видеть'],
    timerSeconds:20 },
  { id:'v092', word:'Желать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['хотеть', 'стремиться', 'мечтать', 'жаждать', 'намереваться', 'просить', 'алкать', 'добиваться'],
    timerSeconds:20 },
  { id:'v093', word:'Наблюдать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['смотреть', 'следить', 'замечать', 'созерцать', 'отслеживать', 'изучать', 'присматривать', 'фиксировать'],
    timerSeconds:20 },
  { id:'v094', word:'Замечать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['видеть', 'обнаруживать', 'подмечать', 'примечать', 'фиксировать', 'улавливать', 'осознавать', 'распознавать'],
    timerSeconds:20 },
  { id:'v095', word:'Уважать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['почитать', 'ценить', 'признавать', 'считаться', 'чтить', 'почтительно относиться', 'уважительно относиться', 'преклоняться'],
    timerSeconds:20 },
  { id:'v096', word:'Ценить', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['дорожить', 'уважать', 'оценивать', 'признавать', 'беречь', 'любить', 'придавать значение', 'выделять'],
    timerSeconds:20 },
  { id:'v097', word:'Сиять', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['блестеть', 'сверкать', 'светиться', 'лучиться', 'искриться', 'гореть', 'озаряться', 'сиять ярко'],
    timerSeconds:20 },
  { id:'v098', word:'Блестеть', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['сиять', 'сверкать', 'искриться', 'лосниться', 'светиться', 'блистать', 'мерцать', 'переливаться'],
    timerSeconds:20 },
  { id:'v099', word:'Звучать', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['звенеть', 'слышаться', 'раздаваться', 'греметь', 'отдаваться', 'резонировать', 'звучать громко', 'отзвучивать'],
    timerSeconds:20 },
  { id:'v100', word:'Петь', partOfSpeech:'verb', difficulty:3, lang:'ru',
    synonyms:['исполнять', 'напевать', 'распевать', 'выводить', 'припевать', 'воспевать', 'скандировать', 'интонировать'],
    timerSeconds:20 },
  // ПРИЛАГАТЕЛЬНЫЕ
  { id:'a001', word:'Красивый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['прекрасный', 'великолепный', 'восхитительный', 'изящный', 'привлекательный', 'чудесный', 'обворожительный', 'роскошный'],
    timerSeconds:40 },
  { id:'a002', word:'Умный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['сообразительный', 'мудрый', 'проницательный', 'толковый', 'смышлёный', 'одарённый', 'способный', 'разумный'],
    timerSeconds:40 },
  { id:'a003', word:'Сильный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['мощный', 'крепкий', 'могучий', 'выносливый', 'стойкий', 'непреклонный', 'твёрдый', 'богатырский'],
    timerSeconds:40 },
  { id:'a004', word:'Быстрый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['скорый', 'стремительный', 'молниеносный', 'проворный', 'резвый', 'шустрый', 'динамичный', 'оперативный'],
    timerSeconds:40 },
  { id:'a005', word:'Яркий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['насыщенный', 'сияющий', 'блестящий', 'выразительный', 'броский', 'интенсивный', 'ослепительный', 'красочный'],
    timerSeconds:40 },
  { id:'a006', word:'Смелый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['храбрый', 'отважный', 'мужественный', 'бесстрашный', 'дерзкий', 'решительный', 'доблестный', 'героический'],
    timerSeconds:40 },
  { id:'a007', word:'Спокойный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['тихий', 'уравновешенный', 'мирный', 'невозмутимый', 'безмятежный', 'сдержанный', 'хладнокровный', 'ровный'],
    timerSeconds:40 },
  { id:'a008', word:'Громкий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['звучный', 'шумный', 'оглушительный', 'звонкий', 'мощный', 'резкий', 'раскатистый', 'гулкий'],
    timerSeconds:40 },
  { id:'a009', word:'Тихий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['негромкий', 'беззвучный', 'спокойный', 'приглушённый', 'молчаливый', 'смирный', 'неслышный', 'тихонький'],
    timerSeconds:40 },
  { id:'a010', word:'Чёткий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['ясный', 'понятный', 'точный', 'внятный', 'определённый', 'резкий', 'отчётливый', 'конкретный'],
    timerSeconds:40 },
  { id:'a011', word:'Мягкий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['нежный', 'плавный', 'бархатный', 'гибкий', 'уступчивый', 'деликатный', 'ласковый', 'податливый'],
    timerSeconds:40 },
  { id:'a012', word:'Жёсткий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['твёрдый', 'суровый', 'строгий', 'крепкий', 'непреклонный', 'резкий', 'жестокий', 'неуступчивый'],
    timerSeconds:40 },
  { id:'a013', word:'Лёгкий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['простой', 'невесомый', 'нетрудный', 'воздушный', 'свободный', 'непринуждённый', 'мягкий', 'быстрый'],
    timerSeconds:40 },
  { id:'a014', word:'Сложный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['трудный', 'запутанный', 'непростой', 'многослойный', 'комплексный', 'замысловатый', 'тяжёлый', 'хитрый'],
    timerSeconds:40 },
  { id:'a015', word:'Новый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['свежий', 'современный', 'недавний', 'новейший', 'обновлённый', 'оригинальный', 'неизвестный', 'молодой'],
    timerSeconds:40 },
  { id:'a016', word:'Старый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['древний', 'прежний', 'ветхий', 'пожилой', 'бывший', 'устаревший', 'давний', 'изношенный'],
    timerSeconds:40 },
  { id:'a017', word:'Добрый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['хороший', 'милосердный', 'сердечный', 'душевный', 'отзывчивый', 'благожелательный', 'ласковый', 'человечный'],
    timerSeconds:40 },
  { id:'a018', word:'Злой', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['сердитый', 'яростный', 'недобрый', 'враждебный', 'жестокий', 'раздражённый', 'свирепый', 'злобный'],
    timerSeconds:40 },
  { id:'a019', word:'Весёлый', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['радостный', 'жизнерадостный', 'забавный', 'смешной', 'беззаботный', 'оживлённый', 'игривый', 'праздничный'],
    timerSeconds:40 },
  { id:'a020', word:'Грустный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['печальный', 'унылый', 'тоскливый', 'мрачный', 'скорбный', 'невесёлый', 'подавленный', 'меланхоличный'],
    timerSeconds:40 },
  { id:'a021', word:'Уверенный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['убеждённый', 'решительный', 'твёрдый', 'спокойный', 'надёжный', 'самостоятельный', 'несомненный', 'стойкий'],
    timerSeconds:40 },
  { id:'a022', word:'Сомнительный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['неясный', 'подозрительный', 'спорный', 'ненадёжный', 'сомненный', 'неуверенный', 'туманный', 'двусмысленный'],
    timerSeconds:40 },
  { id:'a023', word:'Точный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['верный', 'аккуратный', 'меткий', 'правильный', 'безошибочный', 'чёткий', 'достоверный', 'определённый'],
    timerSeconds:40 },
  { id:'a024', word:'Примерный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['приблизительный', 'ориентировочный', 'условный', 'неполный', 'грубый', 'приближённый', 'схематичный', 'общий'],
    timerSeconds:40 },
  { id:'a025', word:'Главный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['основной', 'ведущий', 'ключевой', 'центральный', 'первостепенный', 'важнейший', 'доминирующий', 'базовый'],
    timerSeconds:40 },
  { id:'a026', word:'Важный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['значимый', 'существенный', 'ключевой', 'серьёзный', 'главный', 'ценный', 'принципиальный', 'необходимый'],
    timerSeconds:40 },
  { id:'a027', word:'Маленький', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['небольшой', 'крошечный', 'миниатюрный', 'малый', 'мелкий', 'скромный', 'короткий', 'незначительный'],
    timerSeconds:40 },
  { id:'a028', word:'Большой', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['крупный', 'огромный', 'значительный', 'великий', 'обширный', 'масштабный', 'широкий', 'немалый'],
    timerSeconds:40 },
  { id:'a029', word:'Высокий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['рослый', 'верхний', 'значительный', 'возвышенный', 'большой', 'выдающийся', 'поднятый', 'высочайший'],
    timerSeconds:40 },
  { id:'a030', word:'Низкий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['невысокий', 'нижний', 'малый', 'слабый', 'приглушённый', 'приземлённый', 'низменный', 'пониженный'],
    timerSeconds:40 },
  { id:'a031', word:'Длинный', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['протяжённый', 'долгий', 'растянутый', 'длиннющий', 'обширный', 'продолжительный', 'вытянутый', 'длительный'],
    timerSeconds:40 },
  { id:'a032', word:'Короткий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['краткий', 'недлинный', 'сжатый', 'малый', 'лаконичный', 'быстрый', 'укороченный', 'мимолётный'],
    timerSeconds:40 },
  { id:'a033', word:'Широкий', partOfSpeech:'adjective', difficulty:1, lang:'ru',
    synonyms:['обширный', 'просторный', 'размашистый', 'крупный', 'всеобъемлющий', 'вольный', 'масштабный', 'раздвинутый'],
    timerSeconds:40 },
  { id:'a034', word:'Узкий', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['тесный', 'тонкий', 'ограниченный', 'специализированный', 'малый', 'сжатый', 'узенький', 'стеснённый'],
    timerSeconds:30 },
  { id:'a035', word:'Глубокий', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['бездонный', 'содержательный', 'серьёзный', 'проникновенный', 'основательный', 'низкий', 'глубинный', 'значительный'],
    timerSeconds:30 },
  { id:'a036', word:'Поверхностный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['неглубокий', 'мелкий', 'приблизительный', 'несерьёзный', 'внешний', 'беглый', 'упрощённый', 'плоский'],
    timerSeconds:30 },
  { id:'a037', word:'Богатый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['состоятельный', 'изобильный', 'роскошный', 'обильный', 'щедрый', 'разнообразный', 'полный', 'зажиточный'],
    timerSeconds:30 },
  { id:'a038', word:'Бедный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['нищий', 'скудный', 'убогий', 'небогатый', 'бедственный', 'скромный', 'ограниченный', 'жалкий'],
    timerSeconds:30 },
  { id:'a039', word:'Свободный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['независимый', 'вольный', 'раскованный', 'неограниченный', 'открытый', 'незанятый', 'самостоятельный', 'просторный'],
    timerSeconds:30 },
  { id:'a040', word:'Занятый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['деловой', 'загруженный', 'несвободный', 'увлечённый', 'работающий', 'занимаемый', 'активный', 'перегруженный'],
    timerSeconds:30 },
  { id:'a041', word:'Открытый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['откровенный', 'доступный', 'раскрытый', 'широкий', 'свободный', 'гласный', 'прямой', 'общительный'],
    timerSeconds:30 },
  { id:'a042', word:'Закрытый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['замкнутый', 'скрытый', 'недоступный', 'запертый', 'секретный', 'ограниченный', 'изолированный', 'прикрытый'],
    timerSeconds:30 },
  { id:'a043', word:'Честный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['правдивый', 'порядочный', 'искренний', 'добросовестный', 'прямой', 'открытый', 'неподкупный', 'справедливый'],
    timerSeconds:30 },
  { id:'a044', word:'Лживый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['обманчивый', 'фальшивый', 'неправдивый', 'лукавый', 'неискренний', 'ложный', 'двуличный', 'притворный'],
    timerSeconds:30 },
  { id:'a045', word:'Искренний', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['открытый', 'честный', 'неподдельный', 'душевный', 'сердечный', 'прямой', 'естественный', 'правдивый'],
    timerSeconds:30 },
  { id:'a046', word:'Фальшивый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['поддельный', 'ложный', 'искусственный', 'неискренний', 'притворный', 'обманчивый', 'ненастоящий', 'лицемерный'],
    timerSeconds:30 },
  { id:'a047', word:'Простой', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['лёгкий', 'понятный', 'обычный', 'незамысловатый', 'доступный', 'скромный', 'прямой', 'элементарный'],
    timerSeconds:30 },
  { id:'a048', word:'Стильный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['модный', 'изящный', 'современный', 'элегантный', 'эффектный', 'вкусный', 'утончённый', 'актуальный'],
    timerSeconds:30 },
  { id:'a049', word:'Современный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['актуальный', 'новый', 'модерновый', 'нынешний', 'прогрессивный', 'новейший', 'сегодняшний', 'инновационный'],
    timerSeconds:30 },
  { id:'a050', word:'Классический', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['традиционный', 'образцовый', 'канонический', 'вечный', 'стандартный', 'выверенный', 'эталонный', 'академический'],
    timerSeconds:30 },
  { id:'a051', word:'Энергичный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['активный', 'бодрый', 'живой', 'динамичный', 'напористый', 'деятельный', 'пружинистый', 'темпераментный'],
    timerSeconds:30 },
  { id:'a052', word:'Ленивый', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['праздный', 'медлительный', 'нерасторопный', 'вялый', 'апатичный', 'неактивный', 'сонный', 'расслабленный'],
    timerSeconds:30 },
  { id:'a053', word:'Активный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['деятельный', 'энергичный', 'подвижный', 'инициативный', 'живой', 'работающий', 'динамичный', 'активизированный'],
    timerSeconds:30 },
  { id:'a054', word:'Пассивный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['бездеятельный', 'инертный', 'вялый', 'созерцательный', 'неактивный', 'равнодушный', 'безучастный', 'покорный'],
    timerSeconds:30 },
  { id:'a055', word:'Творческий', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['креативный', 'созидательный', 'изобретательный', 'художественный', 'оригинальный', 'фантазийный', 'новаторский', 'авторский'],
    timerSeconds:30 },
  { id:'a056', word:'Логичный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['разумный', 'последовательный', 'обоснованный', 'связный', 'понятный', 'рациональный', 'закономерный', 'стройный'],
    timerSeconds:30 },
  { id:'a057', word:'Эмоциональный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['чувственный', 'впечатлительный', 'экспрессивный', 'живой', 'страстный', 'нервный', 'выразительный', 'переживающий'],
    timerSeconds:30 },
  { id:'a058', word:'Рациональный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['разумный', 'практичный', 'логичный', 'трезвый', 'расчётливый', 'обдуманный', 'целесообразный', 'осмысленный'],
    timerSeconds:30 },
  { id:'a059', word:'Выразительный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['яркий', 'экспрессивный', 'звучный', 'эмоциональный', 'красноречивый', 'образный', 'броский', 'сильный'],
    timerSeconds:30 },
  { id:'a060', word:'Скучный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['монотонный', 'унылый', 'неинтересный', 'серый', 'однообразный', 'плоский', 'занудный', 'пресный'],
    timerSeconds:30 },
  { id:'a061', word:'Интересный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['увлекательный', 'занимательный', 'любопытный', 'захватывающий', 'привлекательный', 'необычный', 'содержательный', 'интригующий'],
    timerSeconds:30 },
  { id:'a062', word:'Полезный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['нужный', 'ценный', 'практичный', 'важный', 'выгодный', 'благотворный', 'эффективный', 'плодотворный'],
    timerSeconds:30 },
  { id:'a063', word:'Вредный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['опасный', 'пагубный', 'плохой', 'разрушительный', 'неполезный', 'губительный', 'злостный', 'неблагоприятный'],
    timerSeconds:30 },
  { id:'a064', word:'Безопасный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['надёжный', 'защищённый', 'неопасный', 'спокойный', 'устойчивый', 'проверенный', 'гарантированный', 'безвредный'],
    timerSeconds:30 },
  { id:'a065', word:'Опасный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['рискованный', 'угрожающий', 'вредный', 'страшный', 'критический', 'ненадёжный', 'аварийный', 'тревожный'],
    timerSeconds:30 },
  { id:'a066', word:'Надёжный', partOfSpeech:'adjective', difficulty:2, lang:'ru',
    synonyms:['верный', 'крепкий', 'безопасный', 'устойчивый', 'проверенный', 'солидный', 'добротный', 'ответственный'],
    timerSeconds:30 },
  { id:'a067', word:'Хрупкий', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['ломкий', 'нежный', 'тонкий', 'слабый', 'уязвимый', 'деликатный', 'непрочный', 'чувствительный'],
    timerSeconds:20 },
  { id:'a068', word:'Тёплый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['горячеватый', 'мягкий', 'сердечный', 'уютный', 'ласковый', 'душевный', 'согревающий', 'доброжелательный'],
    timerSeconds:20 },
  { id:'a069', word:'Холодный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['ледяной', 'прохладный', 'студёный', 'равнодушный', 'отстранённый', 'сдержанный', 'морозный', 'бесчувственный'],
    timerSeconds:20 },
  { id:'a070', word:'Светлый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['яркий', 'ясный', 'чистый', 'лучистый', 'белый', 'радостный', 'прозрачный', 'озарённый'],
    timerSeconds:20 },
  { id:'a071', word:'Тёмный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['мрачный', 'чёрный', 'сумрачный', 'неясный', 'угрюмый', 'затенённый', 'глухой', 'пасмурный'],
    timerSeconds:20 },
  { id:'a072', word:'Чистый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['аккуратный', 'опрятный', 'незапятнанный', 'ясный', 'прозрачный', 'безупречный', 'свежий', 'стерильный'],
    timerSeconds:20 },
  { id:'a073', word:'Грязный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['нечистый', 'замаранный', 'пыльный', 'мутный', 'неопрятный', 'испачканный', 'нечестный', 'загрязнённый'],
    timerSeconds:20 },
  { id:'a074', word:'Свежий', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['новый', 'прохладный', 'чистый', 'бодрый', 'недавний', 'обновлённый', 'живой', 'неиспорченный'],
    timerSeconds:20 },
  { id:'a075', word:'Усталый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['измученный', 'утомлённый', 'измождённый', 'вялый', 'изнурённый', 'выжатый', 'ослабленный', 'сонный'],
    timerSeconds:20 },
  { id:'a076', word:'Бодрый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['энергичный', 'живой', 'свежий', 'активный', 'весёлый', 'деятельный', 'сильный', 'заряженный'],
    timerSeconds:20 },
  { id:'a077', word:'Серьёзный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['важный', 'ответственный', 'значительный', 'строгий', 'основательный', 'весомый', 'глубокий', 'сосредоточенный'],
    timerSeconds:20 },
  { id:'a078', word:'Забавный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['смешной', 'весёлый', 'потешный', 'комичный', 'курьёзный', 'игривый', 'развлекательный', 'задорный'],
    timerSeconds:20 },
  { id:'a079', word:'Удобный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['комфортный', 'практичный', 'подходящий', 'выгодный', 'сподручный', 'эргономичный', 'приемлемый', 'уместный'],
    timerSeconds:20 },
  { id:'a080', word:'Неудобный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['некомфортный', 'неловкий', 'тесный', 'неподходящий', 'затруднительный', 'тяжёлый', 'непрактичный', 'стеснительный'],
    timerSeconds:20 },
  { id:'a081', word:'Гибкий', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['эластичный', 'пластичный', 'подвижный', 'адаптивный', 'уступчивый', 'мягкий', 'изворотливый', 'вариативный'],
    timerSeconds:20 },
  { id:'a082', word:'Твёрдый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['крепкий', 'жёсткий', 'стойкий', 'непреклонный', 'уверенный', 'прочный', 'неподатливый', 'устойчивый'],
    timerSeconds:20 },
  { id:'a083', word:'Острый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['резкий', 'колкий', 'пронзительный', 'остроумный', 'тонкий', 'пикантный', 'заострённый', 'сильный'],
    timerSeconds:20 },
  { id:'a084', word:'Тупой', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['неострый', 'глупый', 'притуплённый', 'плоский', 'медлительный', 'невыразительный', 'скучный', 'заторможенный'],
    timerSeconds:20 },
  { id:'a085', word:'Редкий', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['нечастый', 'исключительный', 'уникальный', 'единичный', 'дефицитный', 'необычный', 'малочисленный', 'редкостный'],
    timerSeconds:20 },
  { id:'a086', word:'Частый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['постоянный', 'регулярный', 'нередкий', 'частотный', 'обычный', 'повторяющийся', 'систематический', 'многократный'],
    timerSeconds:20 },
  { id:'a087', word:'Дорогой', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['ценный', 'дорогостоящий', 'любимый', 'недешёвый', 'престижный', 'значимый', 'заветный', 'роскошный'],
    timerSeconds:20 },
  { id:'a088', word:'Дешёвый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['недорогой', 'доступный', 'бюджетный', 'низкокачественный', 'копеечный', 'экономный', 'простенький', 'сниженный'],
    timerSeconds:20 },
  { id:'a089', word:'Редакционный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['журнальный', 'публикационный', 'авторский', 'текстовый', 'издательский', 'редакторский', 'материальный', 'медийный'],
    timerSeconds:20 },
  { id:'a090', word:'Грамотный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['образованный', 'компетентный', 'правильный', 'квалифицированный', 'подготовленный', 'умелый', 'осведомлённый', 'профессиональный'],
    timerSeconds:20 },
  { id:'a091', word:'Красноречивый', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['выразительный', 'убедительный', 'говорливый', 'ораторский', 'речистый', 'словесный', 'артистичный', 'вдохновенный'],
    timerSeconds:20 },
  { id:'a092', word:'Бесстрашный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['смелый', 'храбрый', 'отважный', 'неустрашимый', 'дерзкий', 'мужественный', 'доблестный', 'героический'],
    timerSeconds:20 },
  { id:'a093', word:'Решительный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['твёрдый', 'уверенный', 'смелый', 'настойчивый', 'волевой', 'безоговорочный', 'категоричный', 'целеустремлённый'],
    timerSeconds:20 },
  { id:'a094', word:'Нерешительный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['робкий', 'сомневающийся', 'колеблющийся', 'неуверенный', 'мягкий', 'боязливый', 'мнительный', 'слабовольный'],
    timerSeconds:20 },
  { id:'a095', word:'Дружелюбный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['приветливый', 'добрый', 'открытый', 'общительный', 'радушный', 'благожелательный', 'миролюбивый', 'любезный'],
    timerSeconds:20 },
  { id:'a096', word:'Враждебный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['неприязненный', 'злой', 'агрессивный', 'недружелюбный', 'противный', 'недоброжелательный', 'опасный', 'воинственный'],
    timerSeconds:20 },
  { id:'a097', word:'Профессиональный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['квалифицированный', 'мастерский', 'экспертный', 'деловой', 'опытный', 'специализированный', 'компетентный', 'качественный'],
    timerSeconds:20 },
  { id:'a098', word:'Любительский', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['непрофессиональный', 'самодеятельный', 'домашний', 'неопытный', 'начинающий', 'дилетантский', 'простецкий', 'неформальный'],
    timerSeconds:20 },
  { id:'a099', word:'Идеальный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['совершенный', 'безупречный', 'образцовый', 'лучший', 'эталонный', 'прекрасный', 'оптимальный', 'безукоризненный'],
    timerSeconds:20 },
  { id:'a100', word:'Обычный', partOfSpeech:'adjective', difficulty:3, lang:'ru',
    synonyms:['привычный', 'рядовой', 'нормальный', 'стандартный', 'типичный', 'повседневный', 'ординарный', 'заурядный'],
    timerSeconds:20 },
];

const norm = (s: string) =>
  s.toLowerCase().trim().replace(/[.,!?]/g, '').replace(/ё/g, 'е');

export function getRandomVocabWord(excludeIds: string[] = []): VocabWord {
  const available = VOCAB_WORDS_RU.filter((w) => !excludeIds.includes(w.id));
  if (available.length === 0) {
    return VOCAB_WORDS_RU[Math.floor(Math.random() * VOCAB_WORDS_RU.length)];
  }
  return available[Math.floor(Math.random() * available.length)];
}

export function getWordsByDifficulty(difficulty: 1 | 2 | 3): VocabWord[] {
  return VOCAB_WORDS_RU.filter((w) => w.difficulty === difficulty);
}

export function checkSynonym(input: string, synonyms: string[]): boolean {
  const cleaned = norm(input);
  if (!cleaned) return false;
  return synonyms.some((s) => {
    const n = norm(s);
    return n === cleaned || cleaned.includes(n);
  });
}

export function findMatchedSynonym(
  input: string,
  synonyms: string[],
): string | null {
  const cleaned = norm(input);
  if (!cleaned) return null;
  const exact = synonyms.find((s) => norm(s) === cleaned);
  if (exact) return exact;
  return synonyms.find((s) => cleaned.includes(norm(s))) ?? null;
}

export const POS_LABELS_RU: Record<PartOfSpeech, string> = {
  noun: 'существительное',
  verb: 'глагол',
  adjective: 'прилагательное',
};

export const DIFFICULTY_LABEL_RU: Record<1 | 2 | 3, string> = {
  1: 'лёгкое',
  2: 'среднее',
  3: 'сложное',
};

const normalize = (s: string): string =>
  s
    .toLowerCase()
    .trim()
    .replace(/ё/g, 'е')
    .replace(/[^а-яa-z\s]/g, '')
    .replace(/\s+/g, ' ');

const stem = (s: string): string => {
  const w = normalize(s);
  const trimmed = w
    .replace(
      /(ами|ями|ого|его|ому|ему|ой|ей|ую|юю|ые|ие|ых|их|ом|ем|ах|ях|ов|ев|ью|ам|ям|ться|тся|ешь|ишь|ает|яет|ует|ала|ало|али|ила|ило|или|ый|ий|ая|яя|ое|ее|ть|ил|ал|ит|ат|ят|ен|на|ны)$/,
      '',
    )
    .replace(/(ость|ение|ание|ство|тель|ница)$/, '');
  return trimmed || w;
};

const levenshtein = (a: string, b: string): number => {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
    Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0)),
  );
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] =
        a[i - 1] === b[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return dp[m][n];
};

export function checkSynonymAdvanced(
  input: string,
  synonyms: string[],
  foundAlready: string[],
): { matched: string | null; alreadyFound: boolean } {
  const normInput = normalize(input);
  if (!normInput) return { matched: null, alreadyFound: false };
  const stemInput = stem(input);

  for (const syn of synonyms) {
    const normSyn = normalize(syn);
    const stemSyn = stem(syn);

    let isMatch = false;
    if (normInput === normSyn) isMatch = true;
    else if (stemInput === stemSyn && stemInput.length >= 4) isMatch = true;
    else if (normInput.includes(normSyn) && normSyn.length >= 4) isMatch = true;
    else if (normSyn.length >= 6 && levenshtein(normInput, normSyn) === 1)
      isMatch = true;
    else if (stemSyn.length >= 4 && levenshtein(stemInput, stemSyn) <= 1)
      isMatch = true;

    if (isMatch) {
      const already = foundAlready.some(
        (f) => normalize(f) === normSyn,
      );
      if (already) return { matched: null, alreadyFound: true };
      return { matched: syn, alreadyFound: false };
    }
  }
  return { matched: null, alreadyFound: false };
}
