import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

const LANG_KEY = "@kingspeech_lang";

export type Lang = "ru" | "en";

const translations = {
  ru: {
    welcome: "Добро пожаловать!",
    welcomeSub: "Развивай навыки публичных выступлений",
    start: "Начать",
    alreadyHaveAccount: "Уже есть аккаунт? Войти",
    loginTitle: "Войдите, чтобы продолжить",
    loginSub: "Сохраняйте прогресс и достижения",
    continueGoogle: "Войти через Google",
    continueApple: "Войти через Apple ID",
    continueEmail: "Войти по email",
    orDivider: "или",
    profileTitle: "Создайте профиль",
    profileSub: "Пара шагов - и вы готовы к старту!",
    yourName: "Как вас зовут?",
    namePlaceholder: "Введите имя",
    gender: "Выберите пол",
    male: "Мужской",
    female: "Женский",
    continueBtn: "Продолжить",
    onboarding1Title: "Привет, {name}!",
    onboarding1Sub: "Давай покажу, как тут все устроено",
    onboarding2Title: "Главный экран",
    onboarding2Sub: "Здесь ты видишь свой путь - уровни и задания",
    onboarding3Title: "Режимы тренировок",
    onboarding3Sub: "Выбирай режим и нажимай Старт",
    onboarding4Title: "Зарабатывай очки",
    onboarding4Sub: "Проходи уровни, набирай XP и прокачивай свой голос",
    onboarding5Title: "Совет дня",
    onboarding5Sub: "Заходи каждый день - даже 5 минут делают тебя лучше!",
    letsGo: "Погнали!",
    next: "Далее",
    skip: "Пропустить",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Темная",
    logout: "Выйти",
    logoutConfirm: "Вы уверены, что хотите выйти?",
    cancel: "Отмена",
    confirm: "Подтвердить",

    tabPath: "Путь",
    tabInterview: "Interview",
    tabShowtime: "Show Time",
    tabProfile: "Профиль",
    tabSettings: "Настройки",

    soundAndVibration: "ЗВУК И ВИБРАЦИЯ",
    soundEffects: "Звуковые эффекты",
    vibration: "Вибрация",
    notifications: "УВЕДОМЛЕНИЯ",
    pushNotifications: "Push-уведомления",
    dailyReminder: "Ежедневное напоминание",
    reminderTime: "Время напоминания",
    account: "АККАУНТ",
    profile: "Профиль",
    data: "ДАННЫЕ",
    resetProgress: "Сбросить прогресс",
    appVersion: "Версия приложения",
    resetConfirm: "Сбросить весь прогресс? Это действие нельзя отменить.",
    resetTitle: "Сброс прогресса",
    resetMessage: "Это действие нельзя отменить. Весь прогресс будет удален.",
    resetBtn: "Сбросить",
    brandTagline: "Путь к ораторскому мастерству",
    devTools: "РАЗРАБОТЧИК",
    openTesting: "Открытое тестирование",

    xpToNextRank: "XP до следующего ранга",
    tasksCompleted: "Заданий",
    levelsCompleted: "Уровней",
    total: "Всего",
    bestResults: "Лучшие результаты",
    rankSystem: "Система рангов",

    levelNotFound: "Уровень не найден",
    tipsForLevel: "СОВЕТЫ ДЛЯ ЭТОГО УРОВНЯ",
    tasks: "ЗАДАНИЯ",
    bestScore: "Лучший результат",
    strengths: "Сильные стороны",
    recommendations: "Рекомендации",
    retry: "Повторить",
    nextTask: "Дальше",
    levelComplete: "Уровень пройден!",
    earned: "Получено",
    avgScore: "Средний балл",
    toMap: "На карту",
    selfAnalysis: "Самоанализ - это шаг на пути к тому, чтобы стать лучше.",

    clarity: "Четкость",
    confidence: "Уверенность",
    volume: "Громкость",
    tempo: "Темп",
    expressiveness: "Выразительность",
    pauses: "Паузы",

    trainer: "Тренажер",
    freeTraining: "Свободная тренировка. Прогресс не влияет на Путь.",
    chooseTopic: "Выбери тему",
    startTraining: "Начать тренировку",
    speakerTips: "Советы выступающему",
    tipLookForward: "Смотри вперед, а не в текст",
    tipSpeakLouder: "Говори громче, чем обычно",
    tipPause: "Пауза после ключевой фразы - это сила",
    tipStandStraight: "Стой прямо - это передает уверенность",
    tipSmile: "Легкая улыбка расслабляет зал",
    sec: "сек",

    lobbyRecTitle: "Рекомендации",
    lobbyRec1: "Воздержитесь от приема пищи и зевания во время беседы",
    lobbyRec2: "Будьте дружелюбны и открыты в общении",
    lobbyRec3: "Используйте только корректную и уважительную лексику",
    lobbyTip1: "Следите за осанкой",
    lobbyTip2: "Говорите громко, внятно и четко",
    lobbyTip3: "На каждый ответ дается 1 минута",
    lobbyTip4: "Нажмите запись в течение 10 секунд",
    lobbyTips: "Советы",
    startInterview: "Начать интервью",
    interviewWith: "Интервью с {name}",
    analyzingAnswer: "Анализирую ответ...",
    skipQuestion: "Пропустить",
    finish: "Завершить",
    noMicAccess: "Нет доступа к микрофону",
    answerNotRecognized: "Ответ не распознан. Говорите четче и ближе к микрофону.",
    seemsNotHeard: "Кажется, вас не было слышно. Попробуем еще раз?",
    interviewResults: "Результаты интервью",
    growthPoints: "Точки роста",
    backToLobby: "Вернуться",
    todaysTopics: "Темы дня",
    used: "использовано",
    interviewError: "Ошибка интервью",
    interviewLoadError: "Не удалось загрузить интервью",
    interviewCostLabel: "Стоимость",
    interviewCostValue: "5 XP за интервью",
    notEnoughXp: "Недостаточно XP",
    needMoreXp: "Нужно минимум 5 XP для интервью. Пройдите уровни на карте, чтобы заработать XP.",
    ok: "Понятно",

    recordingNotSaved: "Запись не сохранена",
    notCounted: "Не засчитано",
    excellent: "Блестяще!",
    good: "Хорошо!",
    keepGoing: "Продолжай!",
    aiAnalysis: "AI-анализ",
    payAttention: "На что обратить внимание",
    diction: "Дикция",

    nothingSaid: "Ничего не было сказано. Попробуйте снова.",
    goodPerformance: "Хорошее выступление!",
    keepPracticing: "Продолжайте тренироваться.",
    tapToRecord: "Нажми, чтобы начать читать",
    tapToStop: "Нажми, чтобы закончить",
    getReady: "Приготовься",
    countdownGo: "Читай!",
    readingHint: "Читай вслух — текст будет подсвечиваться по мере чтения",
    readingPrepHint: "Перед началом записи прочитай текст про себя — почувствуй ритм и образы",
    goodAnswer: "Хороший ответ, продолжайте развиваться.",
    platformViolation: "Нарушение правил платформы.",
    youParticipated: "Вы участвовали в интервью",
    courageToSpeak: "Смелость говорить вслух",
    thanksForInterview: "Спасибо за интервью! Продолжайте практиковаться.",
    thanksYouDidGreat: "Спасибо за интервью! Вы молодец, продолжайте тренироваться.",

    noisePss: "пс-с...",
    noiseCough: "*кашель*",
    noiseSneeze: "*чихание*",
    noiseHmm: "хм...",
    noiseWhisper: "*шепот*",
    noiseHa: "ха...",
    noiseDots: "...",
    noiseChairCreak: "*скрип стула*",
    noiseSshh: "тс-с!",
    noiseMmm: "мм...",
    noiseRustle: "*шуршание*",
    noiseBravo: "браво!",

    hardToEngageMessage: "Похоже, сегодня вам непросто включиться в диалог - это нормально. Давайте завершим интервью на этом этапе. Вы все равно молодец, что попробовали!",

    portalMaster: "Мастер\nОратор!",
    portalEnd: "Финал\nигры",
    startFromBottom: "Начни с самого низа и иди вверх",

    sectionLabel: "Раздел",
    rankLabel: "Ранг",
    worldsMap: "Карта миров",
    rank1: "Новичок",
    rank2: "Любитель",
    rank3: "Уверенный",
    rank4: "Мастер",
    rank5: "Профи",

    interviewStudio: "Студия интервью",
    noInterviewsToday: "Не доступно",
    nextInterviewIn: "Следующее интервью через",
    allInterviewsDone: "Интервью на сегодня завершены",
    remainingOf: "Осталось {remaining} из {max}",
    scheduleToday: "Расписание на сегодня",
    interviewNofM: "Интервью {n} из {max} с",
    withJenny: "Дженни",
    lost: "ПОТРАЧЕНО",
    passed: "Пройдено",
    pressSpeak: "Нажмите \"Говорить\"",
    excellentScore: "Отлично",
    goodScore: "Хорошо",
    weakScore: "Слабо",
    grammar: "Грамматика",
    stopRecording: "Остановить",
    processingAudio: "Обработка...",
    speak: "Говорить",
    anotherQuestion: "Другой вопрос",
    interviewTerminated: "Интервью прервано",
    violationMessage: "Ваша речь признана неприемлемой и нарушает правила платформы. Игра завершена.",
    interviewComplete: "Интервью завершено",
    myAnswers: "Мои ответы",
    noText: "(нет текста)",
    pauseBtn: "Пауза",
    listenBtn: "Прослушать",
    startAgain: "Начать снова",
    noMicBrowser: "Нет доступа к микрофону. Разрешите доступ в браузере.",
    audioNotRecorded: "Аудио не записано. Попробуйте ещё раз.",
    sessionExpired: "Сессия истекла. Начните интервью заново.",
    networkError: "Ошибка сети. Нажмите микрофон, чтобы повторить.",
    failedToConnect: "Не удалось подключиться к серверу.",
    interviewLost: "Интервью потеряно",
    interviewLostMessage: "Вы не успели ответить вовремя или нарушили правила. Это интервью больше нельзя пройти повторно.",
    interviewLostDesc: "Вы не успели ответить вовремя или нарушили правила. Это интервью больше нельзя пройти повторно.",
    toLobby: "В лобби",
    greeting: "Приветствие",
    recordingInProgress: "Идёт запись речи...",

    speechTopic: "Тема выступления",
    recordingStartsAuto: "Запись голоса начнётся автоматически.",
    timerLabel: "Таймер",
    goOnStage: "Выйти на сцену",
    exit: "Выход",
    exitConfirmTitle: "Вы уверены?",
    exitConfirmMsg: "Прогресс текущего выступления будет потерян.",
    stayBtn: "Остаться",
    leaveBtn: "Выйти",
    hint: "Подсказка",
    tutorialText: "Нажимайте на желтую кнопку со стрелкой, чтобы прокручивать текст выступления",
    tapAnywhere: "Нажмите в любом месте",
    bravo: "Браво!",
    openingPlayback: "Открываем просмотр записи...",

    yourPerformance: "Ваше выступление",
    youAreHere: "Ты здесь",
    performanceRecording: "Запись выступления",
    listenToEnd: "Прослушайте запись до конца, чтобы продолжить",
    aiAnalyzing: "AI анализирует выступление...",
    whatToEvaluate: "Что оценить в себе",
    evalQ1: "Насколько уверенно звучит голос?",
    evalQ2: "Есть ли ненужные паузы или слова-паразиты?",
    evalQ3: "Слышна ли выразительность в ключевых местах?",
    evalQ4: "Как звучит темп - не слишком быстро/медленно?",
    evalQ5: "Чувствуется ли эмоция в голосе?",
    again: "Снова",
    noSound: "Нет звука",
    forward: "Дальше",
    voice: "Голос",
    recordingNotSavedFallback: "Запись не сохранена. Отличная работа - продолжайте практиковаться!",
    couldNotReadRecording: "Не удалось прочитать запись. Хорошее выступление!",
    goodPerformanceFallback: "Хорошее выступление! Продолжайте развиваться.",
    analysisUnavailable: "Анализ временно недоступен. Хорошее выступление!",

    recRecording: "Идёт запись...",
    recReady: "Запись готова",
    recPlaying: "Воспроизведение...",
    recSend: "Отправить",
    recListen: "Слушать",
    recTapToStart: "Нажми, чтобы начать запись",

    fallbackTopic1: "Ваша личная жизнь",
    fallbackTopic2: "Счастье и смысл жизни",
    interviewer: "Интервьюер",
    greetingLabel: "Приветствие",
    questionNofM: "Вопрос {n} из {max}",
    speakWordsAppear: "Говорите - ваши слова появятся здесь...",
    recordingSpeech: "Идёт запись речи...",
    nextQuestion: "Следующий вопрос",

    nextLevel: "Далее",
    allLevelsDone: "Все уровни пройдены!",
    exitTaskTitle: "Выйти из задания?",
    exitTaskMsg: "Прогресс этого задания не сохранится",
    timeLabel: "ВРЕМЯ",
    okBtn: "OK",
  },
  en: {
    welcome: "Welcome!",
    welcomeSub: "Develop your public speaking skills",
    start: "Get Started",
    alreadyHaveAccount: "Already have an account? Sign in",
    loginTitle: "Sign in to continue",
    loginSub: "Save your progress and achievements",
    continueGoogle: "Continue with Google",
    continueApple: "Continue with Apple",
    continueEmail: "Continue with Email",
    orDivider: "or",
    profileTitle: "Create your profile",
    profileSub: "Just a couple steps to get started!",
    yourName: "What's your name?",
    namePlaceholder: "Enter your name",
    gender: "Select gender",
    male: "Male",
    female: "Female",
    continueBtn: "Continue",
    onboarding1Title: "Hi, {name}!",
    onboarding1Sub: "Let me show you how everything works",
    onboarding2Title: "Home Screen",
    onboarding2Sub: "Here you can see your path - levels and tasks",
    onboarding3Title: "Training Modes",
    onboarding3Sub: "Pick a mode and tap Start",
    onboarding4Title: "Earn Points",
    onboarding4Sub: "Complete levels, earn XP and level up your voice",
    onboarding5Title: "Daily Tip",
    onboarding5Sub: "Come back every day - even 5 minutes makes you better!",
    letsGo: "Let's Go!",
    next: "Next",
    skip: "Skip",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    logout: "Log Out",
    logoutConfirm: "Are you sure you want to log out?",
    cancel: "Cancel",
    confirm: "Confirm",

    tabPath: "Path",
    tabInterview: "Interview",
    tabShowtime: "Show Time",
    tabProfile: "Profile",
    tabSettings: "Settings",

    soundAndVibration: "SOUND & VIBRATION",
    soundEffects: "Sound Effects",
    vibration: "Vibration",
    notifications: "NOTIFICATIONS",
    pushNotifications: "Push Notifications",
    dailyReminder: "Daily Reminder",
    reminderTime: "Reminder Time",
    account: "ACCOUNT",
    profile: "Profile",
    data: "DATA",
    resetProgress: "Reset Progress",
    appVersion: "App Version",
    resetConfirm: "Reset all progress? This action cannot be undone.",
    resetTitle: "Reset Progress",
    resetMessage: "This action cannot be undone. All progress will be deleted.",
    resetBtn: "Reset",
    brandTagline: "Your path to oratory mastery",
    devTools: "DEVELOPER",
    openTesting: "Open Testing",

    xpToNextRank: "XP to next rank",
    tasksCompleted: "Tasks",
    levelsCompleted: "Levels",
    total: "Total",
    bestResults: "Best Results",
    rankSystem: "Rank System",

    levelNotFound: "Level not found",
    tipsForLevel: "TIPS FOR THIS LEVEL",
    tasks: "TASKS",
    bestScore: "Best score",
    strengths: "Strengths",
    recommendations: "Recommendations",
    retry: "Retry",
    nextTask: "Next",
    levelComplete: "Level Complete!",
    earned: "Earned",
    avgScore: "Average Score",
    toMap: "To Map",
    selfAnalysis: "Self-analysis is a step on the path to becoming better.",

    clarity: "Clarity",
    confidence: "Confidence",
    volume: "Volume",
    tempo: "Tempo",
    expressiveness: "Expressiveness",
    pauses: "Pauses",

    trainer: "Trainer",
    freeTraining: "Free training. Progress does not affect the Path.",
    chooseTopic: "Choose a topic",
    startTraining: "Start Training",
    speakerTips: "Speaker Tips",
    tipLookForward: "Look forward, not at the text",
    tipSpeakLouder: "Speak louder than usual",
    tipPause: "A pause after a key phrase is powerful",
    tipStandStraight: "Stand straight - it conveys confidence",
    tipSmile: "A slight smile relaxes the audience",
    sec: "sec",

    lobbyRecTitle: "Recommendations",
    lobbyRec1: "Refrain from eating or yawning during the conversation",
    lobbyRec2: "Be friendly and open in communication",
    lobbyRec3: "Use only respectful and appropriate language",
    lobbyTip1: "Watch your posture",
    lobbyTip2: "Speak loud, clear and articulate",
    lobbyTip3: "You have 1 minute for each answer",
    lobbyTip4: "Press record within 10 seconds",
    lobbyTips: "Tips",
    startInterview: "Start Interview",
    interviewWith: "Interview with {name}",
    analyzingAnswer: "Analyzing answer...",
    skipQuestion: "Skip",
    finish: "Finish",
    noMicAccess: "No microphone access",
    answerNotRecognized: "Answer not recognized. Speak more clearly and closer to the microphone.",
    seemsNotHeard: "It seems you weren't heard. Shall we try again?",
    interviewResults: "Interview Results",
    growthPoints: "Areas for Growth",
    backToLobby: "Go Back",
    todaysTopics: "Today's Topics",
    used: "used",
    interviewError: "Interview Error",
    interviewLoadError: "Failed to load interview",
    interviewCostLabel: "Cost",
    interviewCostValue: "5 XP per interview",
    notEnoughXp: "Not Enough XP",
    needMoreXp: "You need at least 5 XP for an interview. Complete levels on the map to earn XP.",
    ok: "Got it",

    recordingNotSaved: "Recording not saved",
    notCounted: "Not counted",
    excellent: "Excellent!",
    good: "Good!",
    keepGoing: "Keep going!",
    aiAnalysis: "AI Analysis",
    payAttention: "Things to work on",
    diction: "Diction",

    nothingSaid: "Nothing was said. Please try again.",
    goodPerformance: "Good performance!",
    keepPracticing: "Keep practicing.",
    tapToRecord: "Tap to start reading",
    tapToStop: "Tap to finish",
    getReady: "Get ready",
    countdownGo: "Read!",
    readingHint: "Read aloud — the text will highlight as you go",
    readingPrepHint: "Read the text silently first — get a feel for the rhythm and imagery",
    goodAnswer: "Good answer, keep developing.",
    platformViolation: "Platform rules violation.",
    youParticipated: "You participated in the interview",
    courageToSpeak: "Courage to speak out loud",
    thanksForInterview: "Thank you for the interview! Keep practicing.",
    thanksYouDidGreat: "Thank you for the interview! Great job, keep training.",

    noisePss: "psst...",
    noiseCough: "*cough*",
    noiseSneeze: "*sneeze*",
    noiseHmm: "hmm...",
    noiseWhisper: "*whisper*",
    noiseHa: "ha...",
    noiseDots: "...",
    noiseChairCreak: "*chair creak*",
    noiseSshh: "shh!",
    noiseMmm: "mmm...",
    noiseRustle: "*rustle*",
    noiseBravo: "bravo!",

    hardToEngageMessage: "It seems like it's hard to engage today - that's okay. Let's wrap up the interview here. You still did great for trying!",

    portalMaster: "Master\nOrator!",
    portalEnd: "End\ngame",
    startFromBottom: "Start from the bottom and work your way up",

    sectionLabel: "Section",
    rankLabel: "Rank",
    worldsMap: "Worlds map",
    rank1: "Novice",
    rank2: "Amateur",
    rank3: "Confident",
    rank4: "Master",
    rank5: "Pro",

    interviewStudio: "Interview Studio",
    noInterviewsToday: "Not available",
    nextInterviewIn: "Next interview in",
    allInterviewsDone: "Today's interviews completed",
    remainingOf: "{remaining} of {max} remaining",
    scheduleToday: "Today's Schedule",
    interviewNofM: "Interview {n} of {max} with",
    withJenny: "Jenny",
    lost: "LOST",
    passed: "Completed",
    pressSpeak: "Press \"Speak\"",
    excellentScore: "Excellent",
    goodScore: "Good",
    weakScore: "Weak",
    grammar: "Grammar",
    stopRecording: "Stop",
    processingAudio: "Processing...",
    speak: "Speak",
    anotherQuestion: "Another question",
    interviewTerminated: "Interview Terminated",
    violationMessage: "Your speech was deemed inappropriate and violates platform rules. The session has ended.",
    interviewComplete: "Interview Complete",
    myAnswers: "My Answers",
    noText: "(no text)",
    pauseBtn: "Pause",
    listenBtn: "Listen",
    startAgain: "Start Again",
    noMicBrowser: "No microphone access. Please allow access in your browser.",
    audioNotRecorded: "Audio not recorded. Please try again.",
    sessionExpired: "Session expired. Please start a new interview.",
    networkError: "Network error. Tap the mic to try again.",
    failedToConnect: "Failed to connect to server.",
    interviewLost: "Interview Lost",
    interviewLostMessage: "You didn't respond in time or violated the rules. This interview cannot be retried.",
    interviewLostDesc: "You didn't respond in time or violated the rules. This interview cannot be retried.",
    toLobby: "To Lobby",
    greeting: "Greeting",
    recordingInProgress: "Recording speech...",

    speechTopic: "Speech Topic",
    recordingStartsAuto: "Voice recording will start automatically.",
    timerLabel: "Timer",
    goOnStage: "Go On Stage",
    exit: "Exit",
    exitConfirmTitle: "Are you sure?",
    exitConfirmMsg: "Your current speech progress will be lost.",
    stayBtn: "Stay",
    leaveBtn: "Leave",
    hint: "Hint",
    tutorialText: "Tap the yellow arrow button to scroll through the speech text",
    tapAnywhere: "Tap anywhere",
    bravo: "Bravo!",
    openingPlayback: "Opening playback...",

    yourPerformance: "Your Performance",
    youAreHere: "You're here",
    performanceRecording: "Performance Recording",
    listenToEnd: "Listen to the recording to continue",
    aiAnalyzing: "AI is analyzing performance...",
    whatToEvaluate: "What to evaluate",
    evalQ1: "How confident does the voice sound?",
    evalQ2: "Are there unnecessary pauses or filler words?",
    evalQ3: "Is expressiveness heard at key moments?",
    evalQ4: "How's the tempo - not too fast/slow?",
    evalQ5: "Is there emotion in the voice?",
    again: "Again",
    noSound: "No Sound",
    forward: "Next",
    voice: "Voice",
    recordingNotSavedFallback: "Recording not saved. Great job - keep practicing!",
    couldNotReadRecording: "Could not read recording. Good performance!",
    goodPerformanceFallback: "Good performance! Keep improving.",
    analysisUnavailable: "Analysis temporarily unavailable. Good performance!",

    recRecording: "Recording...",
    recReady: "Recording ready",
    recPlaying: "Playing...",
    recSend: "Send",
    recListen: "Listen",
    recTapToStart: "Tap to start recording",

    fallbackTopic1: "Your personal life",
    fallbackTopic2: "Happiness and meaning of life",
    interviewer: "Interviewer",
    greetingLabel: "Greeting",
    questionNofM: "Question {n} of {max}",
    speakWordsAppear: "Speak - your words will appear here...",
    recordingSpeech: "Recording speech...",
    nextQuestion: "Next Question",

    nextLevel: "Next",
    allLevelsDone: "All levels complete!",
    exitTaskTitle: "Exit task?",
    exitTaskMsg: "Progress for this task won't be saved",
    timeLabel: "TIME",
    okBtn: "OK",
  },
};

type TranslationKeys = keyof typeof translations.ru;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKeys, vars?: Record<string, string>) => string;
  isLoaded: boolean;
}

const LangContext = createContext<LangContextValue>({
  lang: "ru",
  setLang: () => {},
  t: (key) => key,
  isLoaded: false,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ru");

  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY)
      .then((v) => {
        if (v === "ru" || v === "en") setLangState(v);
      })
      .finally(() => setIsLoaded(true));
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l);
  };

  const t = (key: TranslationKeys, vars?: Record<string, string>): string => {
    let str: string = (translations[lang] as any)[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, isLoaded }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
