// Pools of task content for modules 7-67.
// Modules 1-6 keep the existing hand-curated tasks (hardcoded in generator).

// ── TONGUE TWISTERS POOL ─────────────────────────────────────────────────────
// Each entry: { ru, en } - one twister, in both languages.
export const TWISTERS = [
  { ru: "Расскажите про покупки. Про какие про покупки? Про покупки, про покупки, про покупочки мои.", en: "Peter Piper picked a peck of pickled peppers." },
  { ru: "На дворе трава, на траве дрова. Не руби дрова на траве двора.", en: "She sells seashells by the seashore." },
  { ru: "Бык тупогуб, тупогубенький бычок, у быка бела губа была тупа.", en: "How can a clam cram in a clean cream can?" },
  { ru: "Все бобры добры для своих бобрят.", en: "I scream, you scream, we all scream for ice cream." },
  { ru: "Веник веник веничек, на венике бубенчик.", en: "Red leather, yellow leather, red leather, yellow leather." },
  { ru: "Краб крабу сделал грабли. Подал грабли крабу краб.", en: "A proper copper coffee pot." },
  { ru: "Полили ли лилию? Видели ли Лидию?", en: "Six slick slim sycamore saplings." },
  { ru: "Купи кипу пик. Кипу пик купи. Пик кипу купи.", en: "Toy boat. Toy boat. Toy boat." },
  { ru: "На иве галка, на берегу галька.", en: "Unique New York. Unique New York." },
  { ru: "Бомбардир бонбоньерками бомбардировал барышень.", en: "Selfish shellfish. Selfish shellfish." },
  { ru: "Не жалела мама мыла. Мама Милу мылом мыла.", en: "Friendly Frank flips fine flapjacks." },
  { ru: "Пакет под попкорн. Пакет под попкорн.", en: "Truly rural. Truly rural. Truly rural." },
  { ru: "Стоит копна с подприкопёночком, а под копной перепёлка с перепелятами.", en: "Six sleek swans swam swiftly southward." },
  { ru: "Дробью по перепелам да по тетеревам.", en: "Greek grapes. Greek grapes. Greek grapes." },
  { ru: "У осы не усы, не усищи, а усики.", en: "Black bug bit a big black bear." },
  { ru: "Шла Саша по шоссе и сосала сушку.", en: "Eleven benevolent elephants." },
  { ru: "Карл у Клары украл кораллы, а Клара у Карла украла кларнет.", en: "Lesser leather never weathered wetter weather better." },
  { ru: "От топота копыт пыль по полю летит.", en: "A skunk sat on a stump. The stump thunk the skunk stunk." },
  { ru: "Корабли лавировали, лавировали, да не вылавировали.", en: "Brisk brave brigadiers brandished broad bright blades." },
  { ru: "Ехал Грека через реку, видит Грека - в реке рак.", en: "Six sticky skeletons. Six sticky skeletons." },
  { ru: "Тридцать три корабля лавировали, да не вылавировали.", en: "The sixth sick sheik's sixth sheep's sick." },
  { ru: "Четыре черненьких чумазеньких чертенка чертили чертеж.", en: "Imagine an imaginary menagerie manager." },
  { ru: "Ткет ткач ткани на платки Тане.", en: "Fresh French fried fly fritters." },
  { ru: "Сшит колпак, да не по-колпаковски.", en: "Through three cheese trees three free fleas flew." },
  { ru: "Цапля чахла, цапля сохла, цапля сдохла.", en: "Wayne went to Wales to watch walruses." },
  { ru: "Шесть мышат в шалаше шуршат.", en: "Sheena leads, Sheila needs." },
  { ru: "Мама мыла Милу мылом, Мила мыло не любила.", en: "Cooks cook cupcakes quickly." },
  { ru: "Рыла свинья белорыла, тупорыла, полдвора рылом изрыла.", en: "Stupid superstition. Stupid superstition." },
  { ru: "В четверг четвёртого числа в четыре с четвертью часа.", en: "Roberta ran rings around the Roman ruins." },
  { ru: "Протокол про протокол протоколом запротоколировали.", en: "Six Czech cricket critics." },
  { ru: "Королева кавалеру каравеллу подарила.", en: "She stood on the balcony, inexplicably mimicking him hiccuping." },
  { ru: "Семь раз отмерь - один раз отрежь.", en: "Can you can a can as a canner can can a can?" },
  { ru: "Тише едешь - дальше будешь.", en: "I saw Susie sitting in a shoeshine shop." },
  { ru: "Слово не воробей - вылетит, не поймаешь.", en: "Ed had edited it." },
  { ru: "Язык мой - враг мой.", en: "Knapsack straps." },
  { ru: "Около кола колокола, около ворот коловорот.", en: "Crisp crusts crackle crunchily." },
  { ru: "Везет Сенька Саньку с Сонькой на санках.", en: "The thirty-three thieves thought they thrilled the throne." },
  { ru: "Пирожки с потрошками, повар их потрошил.", en: "Quick kiss. Quicker kiss. Quickest kiss." },
  { ru: "Купила бабуся бусы Марусе.", en: "Which witch wished which wicked wish?" },
  { ru: "Мокрая погода размокропогодилась.", en: "Pad kid poured curd pulled cod." },
  { ru: "Стоит, стоит у ворот бык тупогубенький.", en: "Two tried and true tridents." },
  { ru: "Сорок сорок в короткий срок съели сырок.", en: "Lily ladles little Letty's lentil soup." },
  { ru: "На горе Арарат рвала Варвара виноград.", en: "Eddie edited it." },
  { ru: "Жужжит над жимолостью жук, тяжёлый на жуке кожух.", en: "Birdie birdie in the sky." },
  { ru: "Около кола три хвоя вьются.", en: "Cheap ship trip." },
  { ru: "Маланья-болтунья молоко болтала, выбалтывала, не выболтала.", en: "Tie twine to three tree twigs." },
  { ru: "Тигр в клетке, тигрята тоже там.", en: "Six sharp smart sharks." },
  { ru: "Прыгают на языке скороговорки, как караси на сковородке.", en: "I wish to wish the wish you wish to wish." },
  { ru: "Дятел дуб долбил, да не выдолбил.", en: "Big black bug bit a big black dog." },
  { ru: "Плыли мы плыли, до Кобрина доплыли.", en: "She sees cheese." },
];

// ── READING POOLS (3 categories) ─────────────────────────────────────────────
// Reading levels cycle through three categories: prose → poetry → fable.
// Module N picks category by (N-1) % 3 and pool index by Math.floor((N-1)/3).
// Each entry: { authorRu, titleRu, authorEn, titleEn, category, stanzas: [{ru,en}, x3] }
// All texts are taken from real, well-known classical works.

// Category 1: PROSE — excerpts from Russian/English classical novels and stories.
export const PROSE_PIECES = [
  {
    authorRu: "Лев Толстой", titleRu: "Анна Каренина",
    authorEn: "Leo Tolstoy", titleEn: "Anna Karenina",
    category: "prose",
    stanzas: [
      { ru: "Все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему.",
        en: "All happy families are alike; each unhappy family is unhappy in its own way." },
      { ru: "Всё смешалось в доме Облонских. Жена узнала, что муж был в связи с бывшею в их доме француженкою-гувернанткой, и объявила мужу, что не может жить с ним в одном доме.",
        en: "Everything was in confusion in the Oblonskys' house. The wife had discovered that the husband was carrying on an intrigue with a French girl, who had been a governess in their family, and she had announced to her husband that she could not go on living in the same house with him." },
      { ru: "Положение это продолжалось уже третий день и мучительно чувствовалось и самими супругами, и всеми членами семьи, и домочадцами.",
        en: "This position of affairs had now lasted three days, and was keenly felt by the husband and wife themselves, as well as by all the members of their family and household." },
    ],
  },
  {
    authorRu: "Антон Чехов", titleRu: "Дама с собачкой",
    authorEn: "Anton Chekhov", titleEn: "The Lady with the Dog",
    category: "prose",
    stanzas: [
      { ru: "Говорили, что на набережной появилось новое лицо: дама с собачкой. Дмитрий Дмитрич Гуров, проживший в Ялте уже две недели и привыкший тут, тоже стал интересоваться новыми лицами.",
        en: "It was said that a new person had appeared on the sea-front: a lady with a little dog. Dmitri Dmitrich Gurov, who had by then been a fortnight at Yalta, and so was fairly at home there, had begun to take an interest in new arrivals." },
      { ru: "Сидя в павильоне у Верне, он видел, как по набережной прошла молодая дама, невысокого роста блондинка, в берете; за нею бежал белый шпиц.",
        en: "Sitting in Verney's pavilion, he saw, walking on the sea-front, a fair-haired young lady of medium height, wearing a beret; a white Pomeranian dog was running behind her." },
      { ru: "И потом он встречал её в городском саду и на сквере, по нескольку раз в день. Она гуляла одна, всё в том же берете, с белым шпицем; никто не знал, кто она, и называли её просто так: дама с собачкой.",
        en: "And afterwards he met her in the public gardens and in the square several times a day. She was walking alone, always wearing the same beret, and always with the same white dog; no one knew who she was, and every one called her simply 'the lady with the dog.'" },
    ],
  },
  {
    authorRu: "Иван Тургенев", titleRu: "Бежин луг",
    authorEn: "Charles Dickens", titleEn: "A Tale of Two Cities",
    category: "prose",
    stanzas: [
      { ru: "Был прекрасный июльский день, один из тех дней, которые случаются только тогда, когда погода установилась надолго. С самого раннего утра небо ясно; утренняя заря не пылает пожаром: она разливается кротким румянцем.",
        en: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity." },
      { ru: "Солнце - не огнистое, не раскалённое, как во время знойной засухи, не тускло-багровое, как перед бурей, но светлое и приветно лучезарное - мирно всплывает под узкой и длинной тучкой.",
        en: "It was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us." },
      { ru: "Я возвращался с охоты и шёл по аллее сада. Собака бежала впереди меня. Вдруг она уменьшила свои шаги и начала красться, как бы зачуяв перед собою дичь.",
        en: "We were all going direct to Heaven, we were all going direct the other way - in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only." },
    ],
  },
  {
    authorRu: "Николай Гоголь", titleRu: "Мёртвые души",
    authorEn: "Ernest Hemingway", titleEn: "The Old Man and the Sea",
    category: "prose",
    stanzas: [
      { ru: "В ворота гостиницы губернского города NN въехала довольно красивая рессорная небольшая бричка, в какой ездят холостяки: отставные подполковники, штабс-капитаны, помещики, имеющие около сотни душ крестьян, - словом, все те, которых называют господами средней руки.",
        en: "He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish. In the first forty days a boy had been with him." },
      { ru: "В бричке сидел господин, не красавец, но и не дурной наружности, ни слишком толст, ни слишком тонок; нельзя сказать, чтобы стар, однако ж и не так чтобы слишком молод.",
        en: "But after forty days without a fish the boy's parents had told him that the old man was now definitely and finally salao, which is the worst form of unlucky, and the boy had gone at their orders in another boat which caught three good fish the first week." },
      { ru: "Въезд его не произвёл в городе совершенно никакого шума и не был сопровождён ничем особенным; только два русских мужика, стоявшие у дверей кабака против гостиницы, сделали кое-какие замечания, относившиеся, впрочем, более к экипажу, чем к сидевшему в нём.",
        en: "It made the boy sad to see the old man come in each day with his skiff empty and he always went down to help him carry either the coiled lines or the gaff and harpoon and the sail that was furled around the mast." },
    ],
  },
];

// Category 2: POETRY — classical poems with karaoke-style line highlighting.
export const POETRY_PIECES = [
  {
    authorRu: "Тютчев", titleRu: "Весенняя гроза",
    authorEn: "Wordsworth", titleEn: "I Wandered Lonely as a Cloud",
    stanzas: [
      { ru: "Люблю грозу в начале мая,\nКогда весенний, первый гром,\nКак бы резвяся и играя,\nГрохочет в небе голубом.",
        en: "I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils." },
      { ru: "Гремят раскаты молодые,\nВот дождик брызнул, пыль летит,\nПовисли перлы дождевые,\nИ солнце нити золотит.",
        en: "Beside the lake, beneath the trees,\nFluttering and dancing in the breeze.\nContinuous as the stars that shine\nAnd twinkle on the milky way." },
      { ru: "С горы бежит поток проворный,\nВ лесу не молкнет птичий гам,\nИ гам лесной и шум нагорный -\nВсё вторит весело громам.",
        en: "The waves beside them danced; but they\nOut-did the sparkling waves in glee:\nA poet could not but be gay,\nIn such a jocund company." },
    ],
  },
  {
    authorRu: "Лермонтов", titleRu: "Парус",
    authorEn: "Tennyson", titleEn: "The Eagle",
    stanzas: [
      { ru: "Белеет парус одинокий\nВ тумане моря голубом!..\nЧто ищет он в стране далёкой?\nЧто кинул он в краю родном?..",
        en: "He clasps the crag with crooked hands;\nClose to the sun in lonely lands,\nRing'd with the azure world, he stands." },
      { ru: "Играют волны - ветер свищет,\nИ мачта гнётся и скрыпит...\nУвы! он счастия не ищет\nИ не от счастия бежит!",
        en: "The wrinkled sea beneath him crawls;\nHe watches from his mountain walls,\nAnd like a thunderbolt he falls." },
      { ru: "Под ним струя светлей лазури,\nНад ним луч солнца золотой...\nА он, мятежный, просит бури,\nКак будто в бурях есть покой!",
        en: "Above the cliff he holds his sway,\nThe restless winds his only prey,\nAnd watches all the world below." },
    ],
  },
  {
    authorRu: "Маяковский", titleRu: "Послушайте!",
    authorEn: "Whitman", titleEn: "O Captain! My Captain!",
    stanzas: [
      { ru: "Послушайте!\nВедь, если звёзды зажигают -\nзначит - это кому-нибудь нужно?\nЗначит - кто-то хочет, чтобы они были?",
        en: "O Captain! my Captain! our fearful trip is done,\nThe ship has weather'd every rack, the prize we sought is won,\nThe port is near, the bells I hear, the people all exulting,\nWhile follow eyes the steady keel, the vessel grim and daring." },
      { ru: "Значит - это необходимо,\nчтобы каждый вечер\nнад крышами\nзагоралась хоть одна звезда?!",
        en: "But O heart! heart! heart!\nO the bleeding drops of red,\nWhere on the deck my Captain lies,\nFallen cold and dead." },
      { ru: "Послушайте!\nВедь, если звёзды\nзажигают -\nзначит - это кому-нибудь нужно?",
        en: "My Captain does not answer, his lips are pale and still,\nMy father does not feel my arm, he has no pulse nor will,\nBut I with mournful tread,\nWalk the deck my Captain lies." },
    ],
  },
  {
    authorRu: "Блок", titleRu: "Ночь, улица, фонарь, аптека",
    authorEn: "Frost", titleEn: "Stopping by Woods",
    stanzas: [
      { ru: "Ночь, улица, фонарь, аптека,\nБессмысленный и тусклый свет.\nЖиви ещё хоть четверть века -\nВсё будет так. Исхода нет.",
        en: "Whose woods these are I think I know.\nHis house is in the village though;\nHe will not see me stopping here\nTo watch his woods fill up with snow." },
      { ru: "Умрёшь - начнёшь опять сначала,\nИ повторится всё, как встарь:\nНочь, ледяная рябь канала,\nАптека, улица, фонарь.",
        en: "My little horse must think it queer\nTo stop without a farmhouse near\nBetween the woods and frozen lake\nThe darkest evening of the year." },
      { ru: "Ночь, улица, фонарь, аптека,\nБессмысленный и тусклый свет.\nИ повторится всё, как встарь -\nночь, и канал, и фонарь.",
        en: "The woods are lovely, dark and deep,\nBut I have promises to keep,\nAnd miles to go before I sleep,\nAnd miles to go before I sleep." },
    ],
  },
  {
    authorRu: "Пушкин", titleRu: "Я вас любил",
    authorEn: "Byron", titleEn: "She Walks in Beauty",
    stanzas: [
      { ru: "Я вас любил: любовь ещё, быть может,\nВ душе моей угасла не совсем;\nНо пусть она вас больше не тревожит;\nЯ не хочу печалить вас ничем.",
        en: "She walks in beauty, like the night\nOf cloudless climes and starry skies;\nAnd all that's best of dark and bright\nMeet in her aspect and her eyes." },
      { ru: "Я вас любил безмолвно, безнадежно,\nТо робостью, то ревностью томим;\nЯ вас любил так искренно, так нежно,\nКак дай вам Бог любимой быть другим.",
        en: "One shade the more, one ray the less,\nHad half impair'd the nameless grace\nWhich waves in every raven tress,\nOr softly lightens o'er her face." },
      { ru: "Я вас любил - и помню это слово,\nНо повторять его уж не дерзну.\nИ пусть моё спокойное былое\nТеперь у вас не вызовет вину.",
        en: "And on that cheek, and o'er that brow,\nSo soft, so calm, yet eloquent,\nThe smiles that win, the tints that glow,\nBut tell of days in goodness spent." },
    ],
  },
  {
    authorRu: "Ахматова", titleRu: "Мне голос был",
    authorEn: "Dickinson", titleEn: "Hope is the thing with feathers",
    stanzas: [
      { ru: "Мне голос был. Он звал утешно,\nОн говорил: «Иди сюда,\nОставь свой край глухой и грешный,\nОставь Россию навсегда».",
        en: "Hope is the thing with feathers\nThat perches in the soul,\nAnd sings the tune without the words,\nAnd never stops at all." },
      { ru: "«Я кровь от рук твоих отмою,\nИз сердца выну чёрный стыд,\nЯ новым именем покрою\nБоль поражений и обид».",
        en: "And sweetest in the gale is heard;\nAnd sore must be the storm\nThat could abash the little bird\nThat kept so many warm." },
      { ru: "Но равнодушно и спокойно\nРуками я замкнула слух,\nЧтоб этой речью недостойной\nНе осквернился скорбный дух.",
        en: "I've heard it in the chillest land,\nAnd on the strangest sea;\nYet, never, in extremity,\nIt asked a crumb of me." },
    ],
  },
  {
    authorRu: "Цветаева", titleRu: "Моим стихам",
    authorEn: "Yeats", titleEn: "When You Are Old",
    stanzas: [
      { ru: "Моим стихам, написанным так рано,\nЧто и не знала я, что я - поэт,\nСорвавшимся, как брызги из фонтана,\nКак искры из ракет.",
        en: "When you are old and grey and full of sleep,\nAnd nodding by the fire, take down this book,\nAnd slowly read, and dream of the soft look\nYour eyes had once, and of their shadows deep." },
      { ru: "Ворвавшимся, как маленькие черти,\nВ святилище, где сон и фимиам,\nМоим стихам о юности и смерти,\n- Нечитанным стихам! -",
        en: "How many loved your moments of glad grace,\nAnd loved your beauty with love false or true,\nBut one man loved the pilgrim soul in you,\nAnd loved the sorrows of your changing face." },
      { ru: "Разбросанным в пыли по магазинам\n(Где их никто не брал и не берёт!),\nМоим стихам, как драгоценным винам,\nНастанет свой черёд.",
        en: "And bending down beside the glowing bars,\nMurmur, a little sadly, how love fled\nAnd paced upon the mountains overhead,\nAnd hid his face amid a crowd of stars." },
    ],
  },
  {
    authorRu: "Бродский", titleRu: "Не выходи из комнаты",
    authorEn: "Kipling", titleEn: "If",
    stanzas: [
      { ru: "Не выходи из комнаты, не совершай ошибку.\nЗачем тебе Солнце, если ты куришь Шипку?\nЗа дверью бессмысленно всё, особенно - возглас счастья.\nТолько в уборную - и сразу же возвращайся.",
        en: "If you can keep your head when all about you\nAre losing theirs and blaming it on you,\nIf you can trust yourself when all men doubt you,\nBut make allowance for their doubting too." },
      { ru: "О, не выходи из комнаты, не вызывай мотора.\nПотому что пространство сделано из коридора\nИ кончается счётчиком. А если войдёт живая\nМилка, пасть разевая, выгони не раздевая.",
        en: "If you can wait and not be tired by waiting,\nOr being lied about, don't deal in lies,\nOr being hated, don't give way to hating,\nAnd yet don't look too good, nor talk too wise." },
      { ru: "Не выходи из комнаты; считай, что тебя продуло.\nЧто интересней на свете стены и стула?\nЗачем выходить оттуда, куда вернёшься вечером\nТаким же, каким ты был, тем более - изувеченным?",
        en: "Yours is the Earth and everything that's in it,\nAnd - which is more - you'll be a Man, my son!\nIf you can fill the unforgiving minute\nWith sixty seconds' worth of distance run." },
    ],
  },
  {
    authorRu: "Есенин", titleRu: "Отговорила роща золотая",
    authorEn: "Shelley", titleEn: "Ozymandias",
    stanzas: [
      { ru: "Отговорила роща золотая\nБерёзовым, весёлым языком,\nИ журавли, печально пролетая,\nУж не жалеют больше ни о ком.",
        en: "I met a traveller from an antique land,\nWho said: 'Two vast and trunkless legs of stone\nStand in the desert. Near them, on the sand,\nHalf sunk a shattered visage lies.'" },
      { ru: "Кого жалеть? Ведь каждый в мире странник -\nПройдёт, зайдёт и вновь оставит дом.\nО всех ушедших грезит конопляник\nС широким месяцем над голубым прудом.",
        en: "And on the pedestal these words appear:\n'My name is Ozymandias, king of kings:\nLook on my works, ye Mighty, and despair!'\nNothing beside remains." },
      { ru: "Стою один среди равнины голой,\nА журавлей относит ветром в даль,\nЯ полон дум о юности весёлой,\nНо ничего в прошедшем мне не жаль.",
        en: "Round the decay\nOf that colossal wreck, boundless and bare\nThe lone and level sands stretch far away.\nThus passes glory of the world." },
    ],
  },
  {
    authorRu: "Пастернак", titleRu: "Зимняя ночь",
    authorEn: "Keats", titleEn: "Ode on a Grecian Urn",
    stanzas: [
      { ru: "Мело, мело по всей земле\nВо все пределы.\nСвеча горела на столе,\nСвеча горела.",
        en: "Thou still unravish'd bride of quietness,\nThou foster-child of silence and slow time,\nSylvan historian, who canst thus express\nA flowery tale more sweetly than our rhyme." },
      { ru: "Как летом роем мошкара\nЛетит на пламя,\nСлетались хлопья со двора\nК оконной раме.",
        en: "Heard melodies are sweet, but those unheard\nAre sweeter; therefore, ye soft pipes, play on;\nNot to the sensual ear, but, more endear'd,\nPipe to the spirit ditties of no tone." },
      { ru: "Метель лепила на стекле\nКружки и стрелы.\nСвеча горела на столе,\nСвеча горела.",
        en: "When old age shall this generation waste,\nThou shalt remain, in midst of other woe\nThan ours, a friend to man, to whom thou say'st,\n'Beauty is truth, truth beauty.'" },
    ],
  },
];

// Category 3: FABLES — Krylov verses (RU) and Aesop retellings (EN).
// Note: even though Krylov's fables are in verse, they belong to the fable
// category (no karaoke-line highlighting). English uses Aesop prose retellings.
export const FABLES = [
  {
    authorRu: "Иван Крылов", titleRu: "Ворона и Лисица",
    authorEn: "Aesop", titleEn: "The Fox and the Crow",
    category: "fable",
    stanzas: [
      { ru: "Вороне где-то бог послал кусочек сыру;\nНа ель Ворона взгромоздясь,\nПозавтракать-было совсем уж собралась,\nДа призадумалась, а сыр во рту держала.",
        en: "A Crow sat in a tree holding in her beak a piece of cheese that she had stolen. A Fox spied her and longed to have the cheese himself, so he came and stood beneath the tree and looked up." },
      { ru: "На ту беду Лиса близёхонько бежала;\nВдруг сырный дух Лису остановил:\nЛисица видит сыр, Лисица сыром пленена,\nПлутовка к дереву на цыпочках подходит.",
        en: "'Good day, mistress Crow,' he cried. 'How well you are looking today: how glossy your feathers; how bright your eyes. I feel sure your voice must surpass that of other birds, just as your figure does.'" },
      { ru: "Уж сколько раз твердили миру,\nЧто лесть гнусна, вредна; но только всё не впрок,\nИ в сердце льстец всегда отыщет уголок.",
        en: "The Crow lifted up her head and began to caw her best, but the moment she opened her mouth the piece of cheese fell to the ground, only to be snapped up by the Fox. 'That will do,' said he. 'Do not trust flatterers.'" },
    ],
  },
  {
    authorRu: "Иван Крылов", titleRu: "Стрекоза и Муравей",
    authorEn: "Aesop", titleEn: "The Ant and the Grasshopper",
    category: "fable",
    stanzas: [
      { ru: "Попрыгунья Стрекоза\nЛето красное пропела;\nОглянуться не успела,\nКак зима катит в глаза.",
        en: "In a field one summer's day a Grasshopper was hopping about, chirping and singing to its heart's content. An Ant passed by, bearing along with great toil an ear of corn he was taking to the nest." },
      { ru: "Помертвело чисто поле;\nНет уж дней тех светлых боле,\nКак под каждым ей листком\nБыл готов и стол, и дом.",
        en: "'Why not come and chat with me,' said the Grasshopper, 'instead of toiling and moiling in that way?' 'I am helping to lay up food for the winter,' said the Ant, 'and recommend you to do the same.'" },
      { ru: "«Ты всё пела? это дело:\nТак поди же, попляши!» -\nГоворит ей Муравей.\nВот и кончилась басня.",
        en: "'Why bother about winter?' said the Grasshopper; 'we have got plenty of food at present.' But the Ant went on its way and continued its toil. When the winter came the Grasshopper had no food and found itself dying of hunger." },
    ],
  },
  {
    authorRu: "Иван Крылов", titleRu: "Лебедь, Щука и Рак",
    authorEn: "Aesop", titleEn: "The Tortoise and the Hare",
    category: "fable",
    stanzas: [
      { ru: "Когда в товарищах согласья нет,\nНа лад их дело не пойдёт,\nИ выйдет из него не дело, только мука.",
        en: "A Hare was making fun of the Tortoise one day for being so slow. 'Do you ever get anywhere?' he asked with a mocking laugh. 'Yes,' replied the Tortoise, 'and I get there sooner than you think.'" },
      { ru: "Однажды Лебедь, Рак да Щука\nВезти с поклажей воз взялись,\nИ вместе трое все в него впряглись;\nИз кожи лезут вон, а возу всё нет ходу!",
        en: "The Hare laughed at the Tortoise's words, but agreed to a race. The Fox was to set the course and judge the finish. The Hare started off so fast he was soon far ahead, then thought he would take a nap." },
      { ru: "Поклажа бы для них казалась и легка:\nДа Лебедь рвётся в облака,\nРак пятится назад, а Щука тянет в воду.\nКто виноват из них, кто прав, - судить не нам.",
        en: "Meanwhile the Tortoise kept going slowly but steadily. He passed the place where the Hare was sleeping and was nearing the goal. The Hare awoke and ran his swiftest, but the Tortoise had reached the goal. Slow and steady wins the race." },
    ],
  },
  {
    authorRu: "Иван Крылов", titleRu: "Слон и Моська",
    authorEn: "Aesop", titleEn: "The Lion and the Mouse",
    category: "fable",
    stanzas: [
      { ru: "По улицам Слона водили,\nКак видно, напоказ.\nИзвестно, что Слоны в диковинку у нас,\nТак за Слоном толпы зевак ходили.",
        en: "A Lion lay asleep in the forest, his great head resting on his paws. A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose." },
      { ru: "Отколе ни возьмись, навстречу Моська им.\nУвидевши Слона, ну на него метаться,\nИ лаять, и визжать, и рваться,\nНу так и лезет в драку с ним.",
        en: "Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her. 'Spare me!' begged the poor Mouse. 'Please let me go and some day I will surely repay you.' The Lion was much amused and let her go." },
      { ru: "«Соседка, перестань срамиться, -\nЕй Шавка говорит, - тебе ль с Слоном возиться?»\n«Эх, эх! - ей Моська отвечает, -\nВот то-то мне и духу придаёт,\nЧто я, совсем без драки,\nМогу попасть в большие забияки».",
        en: "Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. The Mouse heard his angry roar and ran to help. She gnawed the ropes until the Lion was free. A kindness is never wasted." },
    ],
  },
  {
    authorRu: "Иван Крылов", titleRu: "Квартет",
    authorEn: "Aesop", titleEn: "The Boy Who Cried Wolf",
    category: "fable",
    stanzas: [
      { ru: "Проказница-Мартышка,\nОсёл,\nКозёл\nДа косолапый Мишка\nЗатеяли сыграть Квартет.",
        en: "A Shepherd Boy tended his master's sheep near a dark forest. It was lonely for him watching the flock, so he devised a plan to amuse himself. He ran down toward the village calling out 'Wolf, Wolf!'" },
      { ru: "Достали нот, баса, альта, две скрипки\nИ сели на лужок под липки -\nПленять своим искусством свет.\nУдарили в смычки, дерут, а толку нет.",
        en: "The villagers came running with pitchforks to drive the Wolf away. But when they arrived at the top of the hill, they found the boy doubled up with laughter at the trick he had played on them. A few days later he tried the same trick again." },
      { ru: "«А вы, друзья, как ни садитесь,\nВсё в музыканты не годитесь», -\nИм отвечает Соловей.\nЧтоб музыкантом быть, так надобно уменье.",
        en: "Then one day a Wolf really did come out from the forest. The Boy cried out 'Wolf, Wolf!' even louder than before. But the villagers thought he was trying to fool them again, and so they didn't come. Liars are not believed even when they speak the truth." },
    ],
  },
];

// ── WARMUP TEMPLATES ─────────────────────────────────────────────────────────
// 8 progressive sets cycling through skills. Each set has 3 tasks.
// {ru, en} per task. Module N (>=7) uses set ((N-7) % 8).
export const WARMUP_SETS = [
  // Set 0: breathing
  [
    { titleRu: "Глубокий вдох", titleEn: "Deep breath",
      instructionRu: "Сделай глубокий вдох через нос, медленный выдох через рот. Произнеси фразу на одном выдохе.",
      instructionEn: "Take a deep breath through your nose and exhale slowly through your mouth. Say the phrase on a single exhale.",
      contentRu: "Воздух наполняет меня. Я спокоен. Мой голос рождается из дыхания.",
      contentEn: "Air fills me. I am calm. My voice is born from my breath.",
      tipsRu: ["Плечи опущены", "Дыши животом", "Не торопись"],
      tipsEn: ["Shoulders relaxed", "Breathe with the belly", "Don't rush"] },
    { titleRu: "Длинная фраза", titleEn: "Long phrase",
      instructionRu: "Произнеси длинное предложение на одном дыхании. Без пауз.",
      instructionEn: "Say a long sentence on a single breath, with no pauses.",
      contentRu: "Когда я говорю спокойно и ровно, мой голос звучит уверенно и мои слова доходят до каждого слушателя.",
      contentEn: "When I speak calmly and evenly, my voice sounds confident and my words reach every listener.",
      tipsRu: ["Распредели дыхание", "Не сжимай горло", "Финал - чёткий"],
      tipsEn: ["Distribute the breath", "Don't squeeze the throat", "Clear finish"] },
    { titleRu: "Контролируемый выдох", titleEn: "Controlled exhale",
      instructionRu: "Произнеси фразу медленно, контролируя поток воздуха.",
      instructionEn: "Say the phrase slowly, controlling the airflow.",
      contentRu: "Я владею своим дыханием. Я владею своим голосом. Я владею своей речью.",
      contentEn: "I control my breath. I control my voice. I control my speech.",
      tipsRu: ["Каждое слово - отдельно", "Воздух не вырывается", "Голос ровный"],
      tipsEn: ["Each word separate", "Air doesn't burst out", "Voice steady"] },
  ],
  // Set 1: articulation
  [
    { titleRu: "Чёткие согласные", titleEn: "Sharp consonants",
      instructionRu: "Прочитай фразу, акцентируя каждый согласный звук.",
      instructionEn: "Read the phrase, emphasizing every consonant sound.",
      contentRu: "Точные слова - точная мысль. Чёткая речь - ясный смысл.",
      contentEn: "Precise words - precise thought. Sharp speech - clear meaning.",
      tipsRu: ["Губы работают", "Кончик языка активен", "Не глотай окончания"],
      tipsEn: ["Lips engaged", "Tongue tip active", "Don't swallow endings"] },
    { titleRu: "Открытые гласные", titleEn: "Open vowels",
      instructionRu: "Произнеси фразу с особым акцентом на гласные звуки.",
      instructionEn: "Say the phrase with special emphasis on vowel sounds.",
      contentRu: "Открой рот шире. Пусть голос звучит полно и свободно.",
      contentEn: "Open your mouth wider. Let your voice sound full and free.",
      tipsRu: ["Челюсть расслаблена", "Гласные - длинные", "Голос не зажат"],
      tipsEn: ["Jaw relaxed", "Vowels long", "Voice unrestricted"] },
    { titleRu: "Чистая дикция", titleEn: "Clean diction",
      instructionRu: "Произнеси фразу так, чтобы каждый звук был кристально чист.",
      instructionEn: "Say the phrase so every sound is crystal clear.",
      contentRu: "Безупречная дикция - визитная карточка оратора. Каждое слово на своём месте.",
      contentEn: "Flawless diction is the speaker's calling card. Every word in its place.",
      tipsRu: ["Не торопись", "Артикулируй", "Слышь себя"],
      tipsEn: ["Don't rush", "Articulate", "Listen to yourself"] },
  ],
  // Set 2: dynamics
  [
    { titleRu: "Тихо и громко", titleEn: "Quiet and loud",
      instructionRu: "Произнеси первую часть тихо, вторую - громко. Контраст.",
      instructionEn: "Say the first part quietly, the second loudly. Contrast.",
      contentRu: "Иногда шёпот сильнее крика. А иногда нужно говорить во весь голос.",
      contentEn: "Sometimes a whisper is stronger than a shout. And sometimes you must speak at full voice.",
      tipsRu: ["Контраст максимальный", "Шёпот - чёткий", "Громкое - не крик"],
      tipsEn: ["Maximum contrast", "Whisper clearly", "Loud is not a shout"] },
    { titleRu: "Скорость и пауза", titleEn: "Speed and pause",
      instructionRu: "Говори быстро, потом сделай паузу. Снова быстро. Снова пауза.",
      instructionEn: "Speak fast, then pause. Then fast again. Then pause again.",
      contentRu: "Быстро - и стоп. Снова быстро - и снова стоп. Темп - инструмент оратора.",
      contentEn: "Fast - and stop. Fast again - and stop again. Tempo is the speaker's instrument.",
      tipsRu: ["Паузы - полная тишина", "Скорость не теряет чёткости", "Контроль - всегда"],
      tipsEn: ["Pauses - full silence", "Speed without losing clarity", "Always in control"] },
    { titleRu: "Полный диапазон", titleEn: "Full range",
      instructionRu: "Используй весь диапазон голоса: от шёпота до силы.",
      instructionEn: "Use the full range of your voice: from whisper to power.",
      contentRu: "Мой голос - это инструмент. Я владею им полностью. Каждый оттенок - под контролем.",
      contentEn: "My voice is an instrument. I command it completely. Every shade is under control.",
      tipsRu: ["Не бойся крайностей", "Переходы плавные", "Чувствуй голос"],
      tipsEn: ["Don't fear extremes", "Smooth transitions", "Feel the voice"] },
  ],
  // Set 3: resonance
  [
    { titleRu: "Грудной резонанс", titleEn: "Chest resonance",
      instructionRu: "Произнеси фразу низким голосом, чувствуя вибрацию в груди.",
      instructionEn: "Say the phrase in a low voice, feeling vibration in your chest.",
      contentRu: "Мой голос идёт из глубины. Он полон. Он силён. Он мой.",
      contentEn: "My voice comes from the depth. It is full. It is strong. It is mine.",
      tipsRu: ["Рука на груди", "Вибрация - ключ", "Низкий регистр"],
      tipsEn: ["Hand on chest", "Vibration is key", "Low register"] },
    { titleRu: "Маска лица", titleEn: "Facial mask",
      instructionRu: "Направь звук в область лица: лоб, нос, скулы.",
      instructionEn: "Direct the sound into your facial area: forehead, nose, cheekbones.",
      contentRu: "Звук резонирует в маске. Голос становится ярким и пробивным.",
      contentEn: "Sound resonates in the mask. The voice becomes bright and carrying.",
      tipsRu: ["Звук в передней части", "Не зажимай горло", "Голос летит"],
      tipsEn: ["Sound in the front", "Don't squeeze the throat", "Voice carries forward"] },
    { titleRu: "Полное звучание", titleEn: "Full sound",
      instructionRu: "Объедини грудной и головной резонанс. Полный звук.",
      instructionEn: "Combine chest and head resonance. Full sound.",
      contentRu: "Полный голос - это сила. Это объём. Это присутствие.",
      contentEn: "A full voice is power. It is volume. It is presence.",
      tipsRu: ["Чувствуй вибрацию везде", "Голос наполняет тебя", "Звук объёмный"],
      tipsEn: ["Feel vibration everywhere", "The voice fills you", "Sound has volume"] },
  ],
  // Set 4: emotion
  [
    { titleRu: "Радость", titleEn: "Joy",
      instructionRu: "Произнеси фразу с искренней радостью. Улыбайся.",
      instructionEn: "Say the phrase with genuine joy. Smile.",
      contentRu: "Сегодня прекрасный день. Я рад быть здесь. Я рад говорить.",
      contentEn: "Today is a wonderful day. I'm glad to be here. I'm glad to speak.",
      tipsRu: ["Улыбка слышна в голосе", "Энергия наружу", "Глаза горят"],
      tipsEn: ["Smile is heard in voice", "Energy outward", "Eyes shine"] },
    { titleRu: "Спокойствие", titleEn: "Calm",
      instructionRu: "Произнеси фразу глубоко, спокойно, уверенно.",
      instructionEn: "Say the phrase deeply, calmly, confidently.",
      contentRu: "Я спокоен. Я уверен. Мои слова идут от ясного ума и спокойного сердца.",
      contentEn: "I am calm. I am sure. My words come from a clear mind and a steady heart.",
      tipsRu: ["Не торопись", "Дыши глубоко", "Тон ровный"],
      tipsEn: ["Don't rush", "Breathe deeply", "Even tone"] },
    { titleRu: "Сила", titleEn: "Strength",
      instructionRu: "Произнеси фразу с внутренней силой, как лидер.",
      instructionEn: "Say the phrase with inner strength, like a leader.",
      contentRu: "Мы сделаем это. Мы готовы. Время пришло.",
      contentEn: "We will do this. We are ready. The time has come.",
      tipsRu: ["Энергия в каждом слове", "Уверенный тон", "Финал - сильный"],
      tipsEn: ["Energy in every word", "Confident tone", "Strong finish"] },
  ],
  // Set 5: projection
  [
    { titleRu: "Голос вперёд", titleEn: "Voice forward",
      instructionRu: "Направь голос в дальнюю точку зала. Не кричи - проецируй.",
      instructionEn: "Direct your voice to the far point of the hall. Don't shout - project.",
      contentRu: "Мой голос летит до последнего ряда. Без напряжения. С силой.",
      contentEn: "My voice carries to the last row. Without strain. With power.",
      tipsRu: ["Опора на дыхании", "Звук - в дальнюю точку", "Не зажимай"],
      tipsEn: ["Support on breath", "Sound to far point", "No tension"] },
    { titleRu: "Без напряжения", titleEn: "Without tension",
      instructionRu: "Говори громко, но без зажатия горла.",
      instructionEn: "Speak loudly, but without throat tension.",
      contentRu: "Громкий голос - не значит напряжённый. Сила приходит из дыхания.",
      contentEn: "A loud voice isn't a strained voice. Power comes from the breath.",
      tipsRu: ["Горло свободно", "Опора - живот", "Звук летит"],
      tipsEn: ["Throat free", "Support from belly", "Sound carries"] },
    { titleRu: "Зал слышит", titleEn: "The room hears",
      instructionRu: "Представь полный зал. Каждое слово долетает до последнего ряда.",
      instructionEn: "Picture a full hall. Every word reaches the last row.",
      contentRu: "Я говорю для всех. Каждый меня слышит. Каждое слово - на месте.",
      contentEn: "I speak for everyone. Everyone hears me. Every word lands.",
      tipsRu: ["Дыхание глубокое", "Голос на опоре", "Не торопись"],
      tipsEn: ["Deep breath", "Voice on support", "Don't rush"] },
  ],
  // Set 6: rhythm
  [
    { titleRu: "Ритм фразы", titleEn: "Phrase rhythm",
      instructionRu: "Произнеси фразу с чётким ритмом. Каждое слово - на месте.",
      instructionEn: "Say the phrase with a clear rhythm. Every word in its place.",
      contentRu: "Раз. Два. Три. Слово за словом. Чётко. Ясно. Уверенно.",
      contentEn: "One. Two. Three. Word by word. Clear. Sharp. Sure.",
      tipsRu: ["Внутренний метроном", "Паузы равные", "Темп стабильный"],
      tipsEn: ["Inner metronome", "Even pauses", "Steady tempo"] },
    { titleRu: "Перемена темпа", titleEn: "Tempo change",
      instructionRu: "Начни медленно, ускоряйся, потом замедли.",
      instructionEn: "Start slowly, speed up, then slow down.",
      contentRu: "Медленно начинаю. Постепенно ускоряюсь. И снова замедляюсь к финалу.",
      contentEn: "I begin slowly. I gradually speed up. And slow down again to the finish.",
      tipsRu: ["Переходы плавные", "Контроль темпа", "Финал - медленный"],
      tipsEn: ["Smooth transitions", "Tempo control", "Slow finish"] },
    { titleRu: "Музыка речи", titleEn: "Music of speech",
      instructionRu: "Произнеси фразу как музыкальную фразу. С мелодией.",
      instructionEn: "Say the phrase like a musical line. With melody.",
      contentRu: "Речь - это музыка. Слова - ноты. Я - дирижёр.",
      contentEn: "Speech is music. Words are notes. I am the conductor.",
      tipsRu: ["Интонация - живая", "Высота меняется", "Слушай мелодию"],
      tipsEn: ["Living intonation", "Pitch changes", "Listen to the melody"] },
  ],
  // Set 7: full mastery
  [
    { titleRu: "Все инструменты", titleEn: "All tools",
      instructionRu: "Используй всё: дыхание, дикцию, динамику, эмоцию.",
      instructionEn: "Use everything: breath, diction, dynamics, emotion.",
      contentRu: "Я мастер своего голоса. Каждый параметр под контролем. Каждое слово - точно.",
      contentEn: "I am the master of my voice. Every parameter under control. Every word exact.",
      tipsRu: ["Сознательно меняй параметры", "Голос - инструмент", "Ты - дирижёр"],
      tipsEn: ["Change parameters consciously", "The voice is an instrument", "You are the conductor"] },
    { titleRu: "Импровизация", titleEn: "Improvisation",
      instructionRu: "Произнеси фразу пять раз - каждый раз по-разному.",
      instructionEn: "Say the phrase five times - each time differently.",
      contentRu: "Я свободен в выборе. Я владею голосом полностью.",
      contentEn: "I am free in my choice. I command my voice fully.",
      tipsRu: ["Не повторяйся", "Каждый раз - новый оттенок", "Слушай себя"],
      tipsEn: ["Don't repeat", "Each time a new shade", "Listen to yourself"] },
    { titleRu: "Финальная разминка", titleEn: "Final warm-up",
      instructionRu: "Произнеси с максимальной выразительностью.",
      instructionEn: "Say with maximum expression.",
      contentRu: "Это мой голос. Он готов. Я готов. Время говорить.",
      contentEn: "This is my voice. It is ready. I am ready. It is time to speak.",
      tipsRu: ["Вложи всё", "Это твой звук", "Время пришло"],
      tipsEn: ["Pour everything in", "This is your sound", "The time has come"] },
  ],
];

// ── INTERVIEW QUESTIONS POOL ─────────────────────────────────────────────────
// Generic deep questions - 1 set of 3 used per module 7+; we cycle through 12 sets
// and append the module theme at the end of question 3 to keep tied to module.
export const INTERVIEW_SETS = [
  [
    { titleRu: "Личный опыт", titleEn: "Personal experience",
      instructionRu: "Поделись историей из жизни. Будь конкретным.",
      instructionEn: "Share a personal story. Be specific.",
      contentRu: "Расскажите о моменте, который изменил вас. Что произошло и какой урок вы вынесли?",
      contentEn: "Tell about a moment that changed you. What happened and what lesson did you take from it?",
      tipsRu: ["Конкретные детали", "Эмоция в голосе", "Финал - вывод"],
      tipsEn: ["Concrete details", "Emotion in voice", "End with insight"] },
    { titleRu: "Глубокий взгляд", titleEn: "Deep view",
      instructionRu: "Ответь вдумчиво, не спеши с выводами.",
      instructionEn: "Answer thoughtfully. Don't rush to conclusions.",
      contentRu: "Что для вас значит быть честным с самим собой? И почему это сложно?",
      contentEn: "What does it mean to you to be honest with yourself? And why is it hard?",
      tipsRu: ["Пауза перед ответом", "Глубокая мысль", "Без шаблонов"],
      tipsEn: ["Pause before answering", "Deep thought", "No clichés"] },
    { titleRu: "Личное мнение", titleEn: "Personal opinion",
      instructionRu: "Сформулируй свою точку зрения уверенно.",
      instructionEn: "State your view confidently.",
      contentRu: "Поделитесь своим взглядом на тему этого модуля. Что для вас здесь важно?",
      contentEn: "Share your view on this module's theme. What matters to you here?",
      tipsRu: ["Уверенный тон", "Своими словами", "Будь убедительным"],
      tipsEn: ["Confident tone", "Your own words", "Be convincing"] },
  ],
  [
    { titleRu: "Поворотный момент", titleEn: "Turning point",
      instructionRu: "Расскажи о решении, которое изменило твою жизнь.",
      instructionEn: "Tell about a decision that changed your life.",
      contentRu: "Какое решение в вашей жизни стало поворотным? Что вы выбрали и почему?",
      contentEn: "What decision in your life became a turning point? What did you choose and why?",
      tipsRu: ["Структура: до - выбор - после", "Эмоции уместны", "Конкретика"],
      tipsEn: ["Structure: before - choice - after", "Emotions welcome", "Specifics"] },
    { titleRu: "Ценности", titleEn: "Values",
      instructionRu: "Назови ценность, которая важна для тебя, и объясни почему.",
      instructionEn: "Name a value that matters to you and explain why.",
      contentRu: "Какая ценность для вас не подлежит компромиссу? Объясните, как она проявляется в вашей жизни.",
      contentEn: "Which value of yours is not subject to compromise? Explain how it shows up in your life.",
      tipsRu: ["Чётко формулируй", "Пример из жизни", "Убедительность"],
      tipsEn: ["Phrase clearly", "Example from life", "Conviction"] },
    { titleRu: "Мнение по теме", titleEn: "View on the theme",
      instructionRu: "Выскажись по теме модуля. Не бойся быть собой.",
      instructionEn: "Speak on the module's theme. Don't be afraid to be yourself.",
      contentRu: "Что вы думаете о теме этого модуля? Поделитесь своим взглядом.",
      contentEn: "What do you think about this module's theme? Share your view.",
      tipsRu: ["Личная позиция", "Без шаблонов", "Уверенно"],
      tipsEn: ["Personal stance", "No clichés", "Confidently"] },
  ],
  [
    { titleRu: "Совет себе", titleEn: "Advice to yourself",
      instructionRu: "Что бы ты сказал себе пять лет назад?",
      instructionEn: "What would you say to yourself five years ago?",
      contentRu: "Если бы вы могли встретить себя пятилетней давности, какие три вещи вы бы сказали и почему именно их?",
      contentEn: "If you could meet yourself from five years ago, what three things would you say and why?",
      tipsRu: ["Тёплый тон", "Конкретика", "Личное"],
      tipsEn: ["Warm tone", "Specifics", "Personal"] },
    { titleRu: "Сложный выбор", titleEn: "Hard choice",
      instructionRu: "Опиши ситуацию, когда выбор был трудным, и как ты решил.",
      instructionEn: "Describe a situation where the choice was hard and how you resolved it.",
      contentRu: "Расскажите о ситуации, в которой пришлось выбирать между важными вещами. Как вы решили?",
      contentEn: "Tell about a situation where you had to choose between important things. How did you decide?",
      tipsRu: ["Контекст коротко", "Логика выбора", "Результат"],
      tipsEn: ["Brief context", "Logic of choice", "Outcome"] },
    { titleRu: "Личное послание", titleEn: "Personal message",
      instructionRu: "Произнеси то, что хочешь сказать миру по теме модуля.",
      instructionEn: "Say what you'd want to tell the world about this module's theme.",
      contentRu: "Если бы вас услышал весь мир, что бы вы сказали по теме этого модуля?",
      contentEn: "If the whole world could hear you, what would you say about this module's theme?",
      tipsRu: ["Главное в начале", "Краткость", "Сила"],
      tipsEn: ["Main thing first", "Brevity", "Strength"] },
  ],
  [
    { titleRu: "Самокритика", titleEn: "Self-critique",
      instructionRu: "Признай свою слабость и расскажи, как с ней работаешь.",
      instructionEn: "Admit a weakness and tell how you're working with it.",
      contentRu: "Какую свою слабость вы признаёте и что делаете, чтобы её преодолеть?",
      contentEn: "Which weakness of yours do you admit, and what are you doing to overcome it?",
      tipsRu: ["Честность", "Без оправданий", "План действий"],
      tipsEn: ["Honesty", "No excuses", "Action plan"] },
    { titleRu: "Гордость", titleEn: "Pride",
      instructionRu: "Расскажи о достижении, которым гордишься, и почему.",
      instructionEn: "Tell about an achievement you're proud of, and why.",
      contentRu: "Какое из ваших достижений значит для вас больше всего? Почему именно оно?",
      contentEn: "Which of your achievements means the most to you? Why this one in particular?",
      tipsRu: ["Без хвастовства", "Эмоция уместна", "Финал - смысл"],
      tipsEn: ["No bragging", "Emotion welcome", "Finish with meaning"] },
    { titleRu: "Совет публике", titleEn: "Advice to the audience",
      instructionRu: "Дай совет аудитории по теме модуля.",
      instructionEn: "Give the audience advice on the module's theme.",
      contentRu: "Какой один совет вы могли бы дать людям, которых волнует тема этого модуля?",
      contentEn: "What one piece of advice would you give to people who care about this module's theme?",
      tipsRu: ["Конкретный совет", "Применимый", "Сильный финал"],
      tipsEn: ["Specific advice", "Applicable", "Strong ending"] },
  ],
];
